openapi: '3.0.3'
info:
  title: VegBankAPI
  version: '1.0'
servers:
  - url: https://api.server.test/v1
paths:
  # takes a project, list of plots, list of observations, list of taxon interpretations
  /vegbank/plotobservations:
    get: 
      summary: takes a list of accession codes and returns a list of plot/observation objects
      parameters: 
        - in: path
          name: accessionCodes
          schema: 
            type: array
            items: 
              type: string
          required: true 
      responses:
        "200":
          description: "found"
          content: 
            application/json:
              schema: 
                type: array
                items:
                  $ref: "#/components/schemas/plotobservation"
    post: 
      summary: takes a list of plot/observation objects and inserts them into the database. 
      requestBody:
        content:
          multipart/form-data:
            schema: 
              type: array
              items: 
                $ref: "#/components/schemas/plotobservation"

      responses:
        "200": 
          description: "completed"
          content: 
            application/json:
              schema: 
                type: array
                items: 
                  type: string
                  description: accession codes for the new created records

  /vegbank/namedplace:
    get: 
      summary: takes a list of named place accession codes and returns the named places. 
      parameters:
        - in: path
          name: accessionCodes
          schema: 
            type: array
            items: 
              type: string
          required: true
      responses: 
        "200":
          description: "found"
          content: 
            application/json:
              schema: 
                type: array
                items: 
                  $ref: "#components/schemas/namedPlace"
    post: 
      summary: upload a list of named places
      requestBody:
        content: 
          application/json:
            schema: 
              type: array
              items:
                $ref: "#/components/schemas/namedPlace"
      responses:
        "200": 
          description: "added successfully"
          content: 
            application/json:
              schema:
                description: List of accession codes for new named places
                type: array
                items: 
                  type: string

components:
  schemas:
    plotobservation:
      type: object
      properties:
        authorPlotCode:
          type: string
        authorObsCode:
          type: string
        locationAccuracy:
          type: string
        confidentialityStatus:
          type: string
        latitude:
          type: number
          format: float
        longitude:
          type: number
          format: float
        authorLocation:
          type: string
        StateOrProvince:
          type: string
        Country:
          type: string
        namedPlaces:
          type: array
          items:
            $ref: "#/components/schemas/namedPlace"
        azimuth:
          type: integer
        shape:
          type: string
        area:
          type: string
        permanence:
          type: string
        elevation:
          type: string
        elevationAccuracy:
          type: string
        slopeAspect:
          type: string
        slopeGradient:
          type: number
          format: float 
        topographicPosition:
          type: string
        landform:
          type: string
        hydrologicRegime:
          type: string
        observationStartDate:
          type: string
          format: date
        observationEndDate:
          type: string
          format: date
        dateAccuracy:
          type: string
        project:
          $ref: "#/components/schemas/project"
        covermethod:
          $ref: "#/components/schemas/coverMethod"
        stratummethod: 
          $ref: "#/components/schemas/stratumMethod"
        stemSizeLimit: 
          type: string
        methodNarrative:
          type: string
        taxonObservationArea:
          type: string
        coverDispersion:
          type: string
        autoTaxonCover:
          type: string
        stemObservationArea:
          type: string
        stemSampleMethod:
          type: string
        plotValidationLevel:
          type: string
        disturbanceObs:
          type: object
          properties:
            #TODO: check types here
            disturbanceType:
              type: string
            disturbanceIntensity:
              type: string
            disturbanceComment:
              type: string
        soilObs:  
          type: object
          properties:
            soilHorizon:
              type: string
            soilTexture:
              type: string
            soilDescription:
              type: string
        soilTaxon: 
          type: object
          properties:
            soilName:
              type: string
            soilLevel:
              type: string
            accessionCode:
              type: string
        plotAccessionCode:
          type: string
        obsAccessionCode:
          type: string

    namedPlace: 
      type: object
      properties:
        placeSystem: 
          type: string
        placeName:
          type: string
        placeCode:
          type: string
        reference:
          type: string
        accessionCode:
          type: string

    project:
      type: object
      properties: 
        plotObservation:
          type: string
        authorPlantName:
          type: string
        reference: 
          type: object
          $ref: "#/components/schemas/reference"
        taxonInferenceArea:
          type: string
        accessionCode: 
          type: string

    stratummethod:
      type: object
      properties: 
        stratumMethodName:
          type: string
        stratumMethodDescription:
          type: string
        reference: 
          type: object
          $ref: "#/components/schemas/reference"
        StratumTypes:
          type: array
          items: 
            $ref: "#/components/schemas/stratumType"
        accessionCode: 
          type: string
    
    reference: 
      type: object
      properties: 
        shortName: 
          type: string
        title: 
          type: string
        pubDate: 
          type: string
        publisher: 
          type: string
        url: 
          type: string
        accessionCode: 
          type: string

    #TODO: fill in properties
    stratumType: 
      type: object
      properties: 
        accessionCode: 
          type: string
    
    #TODO: fill in properties
    stratumMethod: 
      type: object
      properties: 
        accessionCode: 
          type: string
    
    #TODO: fill in properties
    coverMethod: 
      type: object
      properties: 
        accessionCode: 
          type: string