openapi: '3.0.3'
info:
  title: VegBankAPI
  version: '1.0'
servers:
  - url: https://api.server.test/v1
paths:
  # takes a project, list of plots, list of observations, list of taxon interpretations
  /vegbank/plot-observations/{accession_code}:
    get:
      summary: returns a specific plot observation via the observation accession code
      parameters:
        - in: path
          name: accession_code
          schema: 
            type: string
          required: true
      responses: 
        "200":
          description: "found"
          content:
            application/json: 
              schema:
                $ref: "#/components/schemas/plot_observation"
  
  /vegbank/plot-observations:
    get: 
      summary: takes a list of accession codes and returns a list of plot/observation objects. If no parameter is provided, returns all plot observations. 
      parameters: 
        - in: query
          name: accession_codes
          schema: 
            type: array
            items: 
              type: string
      responses:
        "200":
          description: "found"
          content: 
            application/json:
              schema: 
                type: array
                items:
                  $ref: "#/components/schemas/plot_observation"
    post: 
      summary: takes a list of plot/observation objects and inserts them into the database. 
      requestBody:
        content:
          multipart/form-data:
            schema: 
              type: array
              items: 
                $ref: "#/components/schemas/plot_observation"

      responses:
        "200": 
          description: "completed"
          content: 
            application/json:
              schema: 
                type: array
                items: 
                  type: string
                  description: accession codes for the new created records

  /vegbank/named-places/{accession_code}:
      get:
        summary: takes an accession code and returns the named place associated with it.
        parameters: 
          - in: path
            name: accession_code
            schema:
              type: string
            required: true
        responses: 
          "200": 
            description: "found"
            content:
              application/json:
                schema: 
                  $ref: "#/components/schemas/named_place"

  /vegbank/named-places:
    get: 
      summary: takes a list of named place accession codes and returns the named places. If no codes are provided, returns all named places. 
      parameters:
        - in: query
          name: accession_codes
          schema: 
            type: array
            items: 
              type: string
      responses: 
        "200":
          description: "found"
          content: 
            application/json:
              schema: 
                type: array
                items: 
                  $ref: "#components/schemas/named_place"
    post: 
      summary: upload a list of named places
      requestBody:
        content: 
          application/json:
            schema: 
              type: array
              items:
                $ref: "#/components/schemas/named_place"
      responses:
        "200": 
          description: "added successfully"
          content: 
            application/json:
              schema:
                description: List of accession codes for new named places
                type: array
                items: 
                  type: string
  
  /vegbank/references/{accession_code}:
    get:
      summary: takes an accession code and returns the reference associated with it.
      parameters: 
        - in: path
          name: accession_code
          schema:
            type: string
          required: true
      responses: 
        "200": 
          description: "found"
          content:
            application/json:
              schema: 
                $ref: "#/components/schemas/reference"
    
  /vegbank/references:
    get:
      summary: takes an accession code and returns the reference associated with it. If no codes are provided, returns all references. 
      parameters: 
        - in: query
          name: accession_code
          schema:
            type: string
      responses: 
        "200": 
          description: "found"
          content:
            application/json:
              schema: 
                $ref: "#/components/schemas/reference"

  /vegbank/community-name/{accession_code}:
    get: 
      parameters:
        - in: path
          name: blank #NOTE: This table doesn't have accession codes. What should we do here? 
          schema: 
            type: string
          required: true
      responses: 
        "200":
          description: "found"
          content:
            application/json: 
              schema:
                $ref: "#/components/schemas/community_name"

  /vegbank/plant-concept/{accession_code}:
    get:
      summary: returns a specific plant-concept via its accession code
      parameters:
        - in: path
          name: accession_code
          schema: 
            type: string
          required: true
      responses: 
        "200":
          description: "found"
          content:
            application/json: 
              schema:
                $ref: "#/components/schemas/plant_concept"
        
components:
  schemas:
    plot_observation:
      type: object
      properties:
        author_plot_code:
          type: string
        author_obs_code:
          type: string
        location_accuracy:
          type: string
        confidentiality_status:
          type: string
        latitude:
          type: number
          format: float
        longitude:
          type: number
          format: float
        author_location:
          type: string
        state_or_province:
          type: string
        country:
          type: string
        named_places:
          type: array
          items:
            $ref: "#/components/schemas/named_place"
        azimuth:
          type: integer
        shape:
          type: string
        area:
          type: string
        permanence:
          type: string
        elevation:
          type: string
        elevation_accuracy:
          type: string
        slope_aspect:
          type: string
        slope_gradient:
          type: number
          format: float 
        topographic_position:
          type: string
        landform:
          type: string
        hydrologic_regime:
          type: string
        observation_start_date:
          type: string
          format: date
        observation_end_date:
          type: string
          format: date
        date_accuracy:
          type: string
        project:
          $ref: "#/components/schemas/project"
        cover_method:
          $ref: "#/components/schemas/cover_method"
        stratum_method: 
          $ref: "#/components/schemas/stratum_method"
        stem_size_limit: 
          type: string
        method_narrative:
          type: string
        taxon_observation_area:
          type: string
        cover_dispersion:
          type: string
        auto_taxon_cover:
          type: string
        stem_observation_area:
          type: string
        stem_sample_method:
          type: string
        plot_validation_level:
          type: string
        disturbance_obs:
          type: array
          items: 
            $ref: "#/components/schemas/disturbance_obs"
        soil_obs:  
          type: object
          properties:
            soil_horizon:
              type: string
            soil_texture:
              type: string
            soil_description:
              type: string
        soil_taxon: 
          type: object
          $ref: "#/components/schemas/soil_taxon"
        plot_accession_code:
          type: string
        obs_accession_code:
          type: string

    named_place: 
      type: object
      properties:
        place_system: 
          type: string
        place_name:
          type: string
        place_code:
          type: string
        reference:
          type: string
        accession_code:
          type: string

    project:
      type: object
      properties: 
        plot_observation:
          type: string
        author_plantName:
          type: string
        reference: 
          type: object
          $ref: "#/components/schemas/reference"
        taxon_inference_area:
          type: string
        accession_code: 
          type: string

    stratum_method:
      type: object
      properties: 
        stratum_method_name:
          type: string
        stratum_method_description:
          type: string
        reference: 
          type: object
          $ref: "#/components/schemas/reference"
        stratum_types:
          type: array
          items: 
            $ref: "#/components/schemas/stratum_type"
        accession_code: 
          type: string
    
    reference: 
      type: object
      properties: 
        short_name: 
          type: string
        title: 
          type: string
        pub_date: 
          type: string
        publisher: 
          type: string
        url: 
          type: string
        accession_code: 
          type: string

    stratum_type: 
      type: object
      properties: 
        stratum_index: 
          type: string
        stratum_name: 
          type: string
        stratum_description: 
          type: string
        
    cover_method: 
      type: object
      properties: 
        cover_type: 
          type: string
        reference: 
          type: object
          $ref: "#/components/schemas/reference"
        cover_types:
          type: array
          items:
            $ref: "#/components/schemas/cover_type"
        accession_code: 
          type: string
    
    disturbance_obs:
      type: object
      properties:
        disturbance_type:
          type: string
        disturbance_intensity:
          type: string
        disturbance_comment:
          type: string

    soil_taxon:
      type: object
      properties:
        soil_name:
          type: string
        soil_level:
          type: string
        accession_code:
          type: string

    cover_type: 
      type: object
      properties:
        cover_code:
          type: number
        lower_limit: 
          type: number
        upper_limite: 
          type: number
        cover_percent:
          type: number
          format: float
        index_description:
          type: string

    #TODO: needs properties
    plant_name: 
      type: object
      properties: 
        tbd: 
          type: string
    
    #TODO: needs properties, and an identifier if no accession code. 
    community_name:
      type: object
      properties: 
        placeholder:
          type: string
    
    #TODO: needs properties
    reference_party: 
      type: object
      properties: 
        tbd: 
          type: string
    
    plant_concept:
      type: object
      properties: 
        plant_name: 
          type: string
        reference: 
          type: object
          $ref: "#/components/schemas/reference"
        accession_code: 
          type: string

    community_concept:
      type: object
      properties: 
        name: 
          type: string
        reference: 
          type: object
          $ref: "#/components/schemas/reference"
        description: 
          type: string
        accession_code:
          type: string

    party: 
      type: object
      properties: 
        accesison_code: 
          type: string
    
