CREATE TEMP TABLE observation_temp(
    user_ob_code TEXT  NOT NULL,
    vb_pl_code TEXT NOT NULL,
    user_pj_code TEXT,
    vb_pj_code TEXT,
    authorobscode character varying(30),
    obsstartdate timestamp with time zone,
    obsenddate timestamp with time zone,
    dateaccuracy character varying(30),
    dateentered timestamp with time zone DEFAULT now(),
    vb_cm_code TEXT,
    coverdispersion character varying(30),
    autotaxoncover boolean,
    vb_sm_code character varying(30),
    methodnarrative text,
    taxonobservationarea double precision,
    stemsizelimit double precision,
    stemobservationarea double precision,
    stemsamplemethod character varying(30),
    originaldata text,
    effortlevel character varying(30),
    floristicquality character varying(30),
    bryophytequality character varying(30),
    lichenquality character varying(30),
    observationnarrative text,
    landscapenarrative text,
    homogeneity character varying(50),
    phenologicaspect character varying(30),
    standmaturity character varying(50),
    successionalstatus text,
    basalarea double precision,
    hydrologicregime character varying(255),
    soilmoistureregime character varying(30),
    soildrainage character varying(30),
    watersalinity character varying(30),
    waterdepth double precision,
    shoredistance double precision,
    soildepth double precision,
    organicdepth double precision,
    vb_so_code character varying(30),
    soiltaxonsrc character varying(200),
    percentbedrock double precision,
    percentrockgravel double precision,
    percentwood double precision,
    percentlitter double precision,
    percentbaresoil double precision,
    percentwater double precision,
    percentother double precision,
    nameother character varying(30),
    treeht double precision,
    shrubht double precision,
    fieldht double precision,
    nonvascularht double precision,
    submergedht double precision,
    treecover double precision,
    shrubcover double precision,
    fieldcover double precision,
    nonvascularcover double precision,
    floatingcover double precision,
    submergedcover double precision,
    dominantstratum character varying(40),
    growthform1type character varying(40),
    growthform2type character varying(40),
    growthform3type character varying(40),
    growthform1cover double precision,
    growthform2cover double precision,
    growthform3cover double precision,
    totalcover double precision,
    ob_notes_public boolean,
    ob_notes_mgt boolean,
    hasobservationsynonym boolean 
)