MERGE INTO plot dst
USING plot_temp src
ON FALSE
WHEN MATCHED THEN DO NOTHING
WHEN NOT MATCHED THEN
  INSERT (
    authorplotcode,
    parent_id,
    reallatitude,
    reallongitude,
    locationaccuracy,
    confidentialitystatus,
    confidentialityreason,
    latitude,
    longitude,
    authore,
    authorn,
    authorzone,
    authordatum,
    authorlocation,
    locationnarrative,
    azimuth,
    dsgpoly,
    shape,
    area,
    standsize,
    placementmethod,
    permanence,
    layoutnarrative,
    elevation,
    elevationaccuracy,
    elevationrange,
    slopeaspect,
    minslopeaspect,
    maxslopeaspect,
    slopegradient,
    minslopegradient,
    maxslopegradient,
    topoposition,
    landform,
    surficialdeposits,
    rocktype,
    stateprovince,
    country,
    dateentered,
    submitter_surname,
    submitter_givenname,
    submitter_email,
    notespublic,
    notesmgt
  ) VALUES (
    authorplotcode,
    CAST(SUBSTRING(vb_parent_pl_code, 4) AS INT),
    reallatitude,
    reallongitude,
    locationaccuracy,
    confidentialitystatus,
    confidentialityreason,
    latitude,
    longitude,
    authore,
    authorn,
    authorzone,
    authordatum,
    authorlocation,
    locationnarrative,
    azimuth,
    dsgpoly,
    shape,
    area,
    standsize,
    placementmethod,
    permanence,
    layoutnarrative,
    elevation,
    elevationaccuracy,
    elevationrange,
    slopeaspect,
    minslopeaspect,
    maxslopeaspect,
    slopegradient,
    minslopegradient,
    maxslopegradient,
    topoposition,
    landform,
    surficialdeposits,
    rocktype,
    stateprovince,
    country,
    dateentered,
    submitter_surname,
    submitter_givenname,
    submitter_email,
    pl_notes_public,
    pl_notes_mgt
  )
RETURNING merge_action(),
          src.user_pl_code,
          dst.plot_id,
          'pl.' || dst.plot_id AS vb_pl_code;