## Values overrides for deploying Vegbank in the k8s dev-vegbank-dev context.
## See the helm README for instructions.

## @param auth.accessMode Access mode controlling API behavior.
## - `read_only`: No authentication, no uploads.
## - `open`: No authentication, uploads allowed.
## - `authenticated`: Full authentication and authorization required.
##
auth:
  accessMode: "authenticated"
  ## @param auth.roleName.admin Scope name for the admin role
  ## @param auth.roleName.contributor Scope name for the contributor role
  ## @param auth.roleName.user Scope name for the user role
  ##
  roleName:
    admin: "vegbank-dev:admin"
    contributor: "vegbank-dev:contributor"
    user: "vegbank-dev:user"

replicaCount: 1

image:
  ## Set image pull policy to 'Always' for development to ensure latest image is used
  pullPolicy: Always
  tag: ""  # Override docker image version for development builds

## Uncomment if needed; defaults to false:
# databaseRestore:
#   enabled: true
#   filepath: "vegbank_full_fc_v1.9_pg16_20250924.dump"

ingress:
  enabled: true
  hostname: api-dev2.vegbank.org

resources:
  requests:
    cpu: 500m
    memory: 512Mi
  limits:
    cpu: 2
    memory: 4Gi

flyway:
  dbHost: vegbankdb2-cnpg-rw

database:
  host: vegbankdb2-cnpg-rw

gunicorn:
  ## @param gunicorn.workers Number of worker processes for handling requests.
  ## More workers can handle more requests simultaneously, but note that they also require more cpu
  ## and memory - so be sure to adjust the 'resources:' section accordingly.
  ## A common recommendation for workers is (2 x num_cores) + 1. A default setting of 5 workers is
  ## reasonable, which would require at least 2 cpu cores (2 x 2 + 1). Scaling would ideally be done
  ## by increasing the number of replicas (pods) rather than increasing the number of workers, but
  ## this can be adjusted based on the needs and resources of your environment.
  ##
  workers: 5
  ## @param gunicorn.timeout Workers silent for more than this many seconds are killed and restarted
  ## We override the default 30 seconds, since it's too short for some of VegBank's longer-running
  ## API calls
  ##
  timeout: 2400
  ## @param gunicorn.logLevel Granularity of gunicorn logs (debug|info|warning|error|critical)
  ##
  logLevel: "debug"

  ## @param gunicorn.limitRequestFieldSize The maximum size of HTTP request header fields in bytes. Default is 8KB, but this is upped to 16kb to match the limit set at the auth stage.
  limitRequestFieldSize: 16384 
