## Values overrides for deploying Vegbank in the k8s dev-vegbank-dev context.
## See the helm README for instructions.

## @param auth.accessMode Access mode controlling API behavior.
## - `read_only`: No authentication, no uploads.
## - `open`: No authentication, uploads allowed.
## - `authenticated`: Full authentication and authorization required.
##
auth:
  accessMode: "authenticated"

replicaCount: 1

image:
  ## Set image pull policy to 'Always' for development to ensure latest image is used
  pullPolicy: Always
  tag: ""  # Override docker image version for development builds

## Uncomment if needed; defaults to false:
# databaseRestore:
#   enabled: true
#   filepath: "vegbank_full_fc_v1.9_pg16_20250924.dump"

## @section Probes
livenessProbe:
  initialDelaySeconds: 30
  periodSeconds: 30
  timeoutSeconds: 5
  failureThreshold: 3
  httpGet:
    ## @param livenessProbe.httpGet.path The path to use for the liveness probe.
    path: /
    ## @param livenessProbe.httpGet.port The port to use for the liveness probe.
    port: 8000
readinessProbe:
  initialDelaySeconds: 30
  periodSeconds: 30
  timeoutSeconds: 5
  failureThreshold: 3
  httpGet:
    ## @param readinessProbe.httpGet.path The path to use for the readiness probe.
    path: /
    ## @param readinessProbe.httpGet.port The port to use for the readiness probe.
    port: 8000

## @section Service
## Port and type for the service that will connect the ingress to the Flask API. There is no service section in the ingress 
## as the ingress automatically pulls the default named service for the pod via release name. 
##
service:
  ## @param service.type The type of service to create.
  type: ClusterIP
  ## @param service.port The port on which the service will be exposed.
  port: 8000
  targetPort: 8000

ingress:
  enabled: true
  hostname: api-dev2.vegbank.org

resources:
  requests:
    cpu: 500m
    memory: 512Mi
  limits:
    cpu: 2
    memory: 4Gi

flyway:
  dbHost: vegbankdb2-cnpg-rw

database:
  host: vegbankdb2-cnpg-rw
