CREATE TEMP TABLE plot_temp (
    authorplotcode character varying(30) NOT NULL,
    pl_code character varying(30) NOT NULL,
    rf_code character varying(30),
    parent_pl_code integer,
    reallatitude double precision,
    reallongitude double precision,
    locationaccuracy double precision,
    confidentialitystatus integer NOT NULL,
    confidentialityreason character varying(200),
    latitude double precision,
    longitude double precision,
    authore character varying(20),
    authorn character varying(20),
    authorzone character varying(20),
    authordatum character varying(20),
    authorlocation character varying(200),
    locationnarrative text,
    plotrationalenarrative text,
    azimuth double precision,
    dsgpoly text,
    shape character varying(50),
    area double precision,
    standsize character varying(50),
    placementmethod character varying(50),
    permanence boolean,
    layoutnarrative text,
    elevation double precision,
    elevationaccuracy double precision,
    elevationrange double precision,
    slopeaspect double precision,
    minslopeaspect double precision,
    maxslopeaspect double precision,
    slopegradient double precision,
    minslopegradient double precision,
    maxslopegradient double precision,
    topoposition character varying(90),
    landform character varying(50),
    surficialdeposits character varying(90),
    rocktype character varying(90),
    stateprovince character varying(55),
    country character varying(100),
    dateentered timestamp with time zone DEFAULT now(),
    submitter_surname character varying(100),
    submitter_givenname character varying(100),
    submitter_email character varying(100),
    pl_notes_public boolean,
    pl_notes_mgt boolean,
    pl_revisions boolean
);
