INSERT INTO plot_temp (
    user_pl_code,
    authorplotcode,
    vb_parent_pl_code,
    reallatitude,
    reallongitude,
    locationaccuracy,
    confidentialitystatus,
    confidentialityreason,
    latitude,
    longitude,
    authore,
    authorn,
    authorzone,
    authordatum,
    authorlocation,
    locationnarrative,
    azimuth,
    dsgpoly,
    shape,
    area,
    standsize,
    placementmethod,
    permanence,
    layoutnarrative,
    elevation,
    elevationaccuracy,
    elevationrange,
    slopeaspect,
    minslopeaspect,
    maxslopeaspect,
    slopegradient,
    minslopegradient,
    maxslopegradient,
    topoposition,
    landform,
    surficialdeposits,
    rocktype,
    stateprovince,
    country,
    dateentered,
    submitter_surname,
    submitter_givenname,
    submitter_email,
    pl_notes_public,
    pl_notes_mgt
    )
VALUES(
    %s, %s, %s, %s, %s, 
    %s, %s, %s, %s, %s,
    %s, %s, %s, %s, %s,
    %s, %s, %s, %s, %s,
    %s, %s, %s, %s, %s,
    %s, %s, %s, %s, %s,
    %s, %s, %s, %s, %s,
    %s, %s, %s, %s, %s,
    %s, %s, %s, %s, %s
);