SELECT
    plot.plot_id,
    authorPlotCode,
    reference_ID,
    parent_ID,
    locationAccuracy,
    confidentialityStatus,
    confidentialityReason,
    latitude,
    longitude,
    authorE,
    authorN,
    authorZone,
    authorDatum,
    authorLocation,
    locationNarrative,
    azimuth,
    dsgpoly,
    shape,
    area,
    standSize,
    placementMethod,
    permanence,
    layoutNarrative,
    elevation,
    elevationAccuracy,
    elevationRange,
    slopeAspect,
    minSlopeAspect,
    maxSlopeAspect,
    slopeGradient,
    minSlopeGradient,
    maxSlopeGradient,
    topoPosition,
    landform,
    surficialDeposits,
    rockType,
    plot.accessionCode AS plotAccessionCode,
    plot.notesPublic AS plotNotesPublic,
    plot.notesMgt,
    plot.revisions,
    observation.*
FROM
    plot join observation on plot.plot_id = observation.plot_id
LIMIT 1;