----------------------------------------------------------------------------
-- Creates the identifier table for storing resource identifiers
----------------------------------------------------------------------------

CREATE TABLE identifier (
  identifier_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  vb_table TEXT NOT NULL, -- Name of table holding the identified resource
  vb_table_code TEXT NOT NULL, -- Code representing name of the table
  vb_table_id BIGINT NOT NULL, -- FK holding the PK of the resource
  identifier_type TEXT NOT NULL, -- e.g., AccessionCode, DOI, ORCID, ROR, LOCAL
  identifier_value TEXT NOT NULL, -- e.g., "vb.ob.1234.abcd", "10.1234/abcd", "0000-0002-1825-0097"
  UNIQUE (identifier_type, identifier_value) -- Prevent duplicate mappings
);