----------------------------------------------------------------------------------------------------
-- Step 1: drop any existing views, otherwise PG stops us from modifying the underlying tables
----------------------------------------------------------------------------------------------------
--
-- Generated by this query:
--
-- SELECT DISTINCT
--     'DROP VIEW IF EXISTS "' || vcu.view_schema || '"."' || vcu.view_name || '" CASCADE;'
-- FROM
--     information_schema.view_column_usage vcu
-- JOIN
--     information_schema.columns c
--     ON vcu.table_schema = c.table_schema
--     AND vcu.table_name = c.table_name
--     AND vcu.column_name = c.column_name
-- WHERE
--     vcu.view_schema NOT IN ('pg_catalog', 'information_schema')
--     AND c.data_type = 'character varying';
--
DROP VIEW IF EXISTS "public"."stratumtype_x_observation" CASCADE;
DROP VIEW IF EXISTS "public"."stratumtype_x_stratummethod" CASCADE;
DROP VIEW IF EXISTS "public"."view_all_commnames_code" CASCADE;
DROP VIEW IF EXISTS "public"."view_all_commnames_common" CASCADE;
DROP VIEW IF EXISTS "public"."view_all_commnames_sciname" CASCADE;
DROP VIEW IF EXISTS "public"."view_all_commnames_translated" CASCADE;
DROP VIEW IF EXISTS "public"."view_all_plantnames_code" CASCADE;
DROP VIEW IF EXISTS "public"."view_all_plantnames_common" CASCADE;
DROP VIEW IF EXISTS "public"."view_all_plantnames_sciname" CASCADE;
DROP VIEW IF EXISTS "public"."view_all_plantnames_scinamenoauth" CASCADE;
DROP VIEW IF EXISTS "public"."view_busrule_duplcovercode" CASCADE;
DROP VIEW IF EXISTS "public"."view_busrule_duplstratumtype" CASCADE;
DROP VIEW IF EXISTS "public"."view_busrule_plotsizeshape" CASCADE;
DROP VIEW IF EXISTS "public"."view_commconcept_transl" CASCADE;
DROP VIEW IF EXISTS "public"."view_comminterp_more" CASCADE;
DROP VIEW IF EXISTS "public"."view_csv_taxonimportance" CASCADE;
DROP VIEW IF EXISTS "public"."view_csv_taxonimportance_pre" CASCADE;
DROP VIEW IF EXISTS "public"."view_dbafielddesc_notimpl" CASCADE;
DROP VIEW IF EXISTS "public"."view_export_commclass" CASCADE;
DROP VIEW IF EXISTS "public"."view_export_comminterpretation" CASCADE;
DROP VIEW IF EXISTS "public"."view_export_disturbanceobs" CASCADE;
DROP VIEW IF EXISTS "public"."view_export_observation" CASCADE;
DROP VIEW IF EXISTS "public"."view_export_plot" CASCADE;
DROP VIEW IF EXISTS "public"."view_export_plot_pre" CASCADE;
DROP VIEW IF EXISTS "public"."view_export_soilobs" CASCADE;
DROP VIEW IF EXISTS "public"."view_export_stemlocation" CASCADE;
DROP VIEW IF EXISTS "public"."view_export_taxonalt" CASCADE;
DROP VIEW IF EXISTS "public"."view_export_taxonimportance" CASCADE;
DROP VIEW IF EXISTS "public"."view_export_taxoninterpretation" CASCADE;
DROP VIEW IF EXISTS "public"."view_export_taxonobservation" CASCADE;
DROP VIEW IF EXISTS "public"."view_keywprojplaces" CASCADE;
DROP VIEW IF EXISTS "public"."view_kwhelper_projcontrib" CASCADE;
DROP VIEW IF EXISTS "public"."view_kwhelper_refjournal" CASCADE;
DROP VIEW IF EXISTS "public"."view_kwhelper_refparty" CASCADE;
DROP VIEW IF EXISTS "public"."view_notemb_commclass" CASCADE;
DROP VIEW IF EXISTS "public"."view_notemb_comminterpretation" CASCADE;
DROP VIEW IF EXISTS "public"."view_notemb_disturbanceobs" CASCADE;
DROP VIEW IF EXISTS "public"."view_notemb_observation" CASCADE;
DROP VIEW IF EXISTS "public"."view_notemb_plot" CASCADE;
DROP VIEW IF EXISTS "public"."view_notemb_soilobs" CASCADE;
DROP VIEW IF EXISTS "public"."view_notemb_stemlocation" CASCADE;
DROP VIEW IF EXISTS "public"."view_notemb_taxonalt" CASCADE;
DROP VIEW IF EXISTS "public"."view_notemb_taxonimportance" CASCADE;
DROP VIEW IF EXISTS "public"."view_notemb_taxoninterpretation" CASCADE;
DROP VIEW IF EXISTS "public"."view_notemb_taxonobservation" CASCADE;
DROP VIEW IF EXISTS "public"."view_observation_transl" CASCADE;
DROP VIEW IF EXISTS "public"."view_party_public" CASCADE;
DROP VIEW IF EXISTS "public"."view_party_transl" CASCADE;
DROP VIEW IF EXISTS "public"."view_plantconcept_transl" CASCADE;
DROP VIEW IF EXISTS "public"."view_plotall_withembargo" CASCADE;
DROP VIEW IF EXISTS "public"."view_reference_transl" CASCADE;
DROP VIEW IF EXISTS "public"."view_std_commnames_code" CASCADE;
DROP VIEW IF EXISTS "public"."view_std_commnames_common" CASCADE;
DROP VIEW IF EXISTS "public"."view_std_commnames_sciname" CASCADE;
DROP VIEW IF EXISTS "public"."view_std_commnames_translated" CASCADE;
DROP VIEW IF EXISTS "public"."view_std_plantnames_code" CASCADE;
DROP VIEW IF EXISTS "public"."view_std_plantnames_common" CASCADE;
DROP VIEW IF EXISTS "public"."view_std_plantnames_sciname" CASCADE;
DROP VIEW IF EXISTS "public"."view_std_plantnames_scinamenoauth" CASCADE;
DROP VIEW IF EXISTS "public"."view_taxoninterp_more" CASCADE;
DROP VIEW IF EXISTS "public"."view_taxonobs_distinctid_curr" CASCADE;
DROP VIEW IF EXISTS "public"."view_taxonobs_distinctid_curr_counts_plants" CASCADE;
DROP VIEW IF EXISTS "public"."view_taxonobs_withmaxcover" CASCADE;
----------------------------------------------------------------------------------------------------

----------------------------------------------------------------------------------------------------
-- Step 2: change data types of all 'varchar' columns to 'text' instead, to allow for longer values
----------------------------------------------------------------------------------------------------
--
-- generated by this query:
--
-- SELECT
--     'ALTER TABLE "' || c.table_schema || '"."' || c.table_name ||
--     '" ALTER COLUMN "' || c.column_name || '" TYPE text;' AS migration_script
-- FROM
--     information_schema.columns c
-- JOIN
--     information_schema.tables t
--     ON c.table_schema = t.table_schema AND c.table_name = t.table_name
-- WHERE
--     c.table_schema NOT IN ('pg_catalog', 'information_schema')
--     AND t.table_type = 'BASE TABLE'
--     AND c.data_type = 'character varying'
-- ORDER BY
--     c.table_schema,
--     c.table_name;
--
ALTER TABLE "public"."address" ALTER COLUMN "country" TYPE text;
ALTER TABLE "public"."address" ALTER COLUMN "orgposition" TYPE text;
ALTER TABLE "public"."address" ALTER COLUMN "email" TYPE text;
ALTER TABLE "public"."address" ALTER COLUMN "deliverypoint" TYPE text;
ALTER TABLE "public"."address" ALTER COLUMN "city" TYPE text;
ALTER TABLE "public"."address" ALTER COLUMN "administrativearea" TYPE text;
ALTER TABLE "public"."address" ALTER COLUMN "postalcode" TYPE text;
ALTER TABLE "public"."aux_role" ALTER COLUMN "accessioncode" TYPE text;
ALTER TABLE "public"."aux_role" ALTER COLUMN "rolecode" TYPE text;
ALTER TABLE "public"."aux_role" ALTER COLUMN "roledescription" TYPE text;
ALTER TABLE "public"."commclass" ALTER COLUMN "commlevel" TYPE text;
ALTER TABLE "public"."commclass" ALTER COLUMN "commcode" TYPE text;
ALTER TABLE "public"."commclass" ALTER COLUMN "commname" TYPE text;
ALTER TABLE "public"."commclass" ALTER COLUMN "accessioncode" TYPE text;
ALTER TABLE "public"."commclass" ALTER COLUMN "commframework" TYPE text;
ALTER TABLE "public"."commconcept" ALTER COLUMN "accessioncode" TYPE text;
ALTER TABLE "public"."commcorrelation" ALTER COLUMN "commconvergence" TYPE text;
ALTER TABLE "public"."comminterpretation" ALTER COLUMN "commname" TYPE text;
ALTER TABLE "public"."comminterpretation" ALTER COLUMN "commcode" TYPE text;
ALTER TABLE "public"."comminterpretation" ALTER COLUMN "classconfidence" TYPE text;
ALTER TABLE "public"."comminterpretation" ALTER COLUMN "classfit" TYPE text;
ALTER TABLE "public"."commstatus" ALTER COLUMN "commlevel" TYPE text;
ALTER TABLE "public"."commstatus" ALTER COLUMN "accessioncode" TYPE text;
ALTER TABLE "public"."commstatus" ALTER COLUMN "commconceptstatus" TYPE text;
ALTER TABLE "public"."commusage" ALTER COLUMN "commnamestatus" TYPE text;
ALTER TABLE "public"."commusage" ALTER COLUMN "classsystem" TYPE text;
ALTER TABLE "public"."coverindex" ALTER COLUMN "covercode" TYPE text;
ALTER TABLE "public"."covermethod" ALTER COLUMN "accessioncode" TYPE text;
ALTER TABLE "public"."covermethod" ALTER COLUMN "covertype" TYPE text;
ALTER TABLE "public"."covermethod" ALTER COLUMN "coverestimationmethod" TYPE text;
ALTER TABLE "public"."dba_confidentialitystatus" ALTER COLUMN "confidentialityshorttext" TYPE text;
ALTER TABLE "public"."dba_confidentialitystatus" ALTER COLUMN "confidentialitytext" TYPE text;
ALTER TABLE "public"."dba_cookie" ALTER COLUMN "defaultvalue" TYPE text;
ALTER TABLE "public"."dba_cookie" ALTER COLUMN "viewname" TYPE text;
ALTER TABLE "public"."dba_cookie" ALTER COLUMN "cookiename" TYPE text;
ALTER TABLE "public"."dba_cookielabels" ALTER COLUMN "vieworcookie" TYPE text;
ALTER TABLE "public"."dba_datacache" ALTER COLUMN "data7" TYPE text;
ALTER TABLE "public"."dba_datacache" ALTER COLUMN "data6" TYPE text;
ALTER TABLE "public"."dba_datacache" ALTER COLUMN "data5" TYPE text;
ALTER TABLE "public"."dba_datacache" ALTER COLUMN "data4" TYPE text;
ALTER TABLE "public"."dba_datacache" ALTER COLUMN "data3" TYPE text;
ALTER TABLE "public"."dba_datacache" ALTER COLUMN "data2" TYPE text;
ALTER TABLE "public"."dba_datacache" ALTER COLUMN "cache_label" TYPE text;
ALTER TABLE "public"."dba_datacache" ALTER COLUMN "data10" TYPE text;
ALTER TABLE "public"."dba_datacache" ALTER COLUMN "data9" TYPE text;
ALTER TABLE "public"."dba_datacache" ALTER COLUMN "data8" TYPE text;
ALTER TABLE "public"."dba_datacache" ALTER COLUMN "data1" TYPE text;
ALTER TABLE "public"."dba_datacache" ALTER COLUMN "cache_key" TYPE text;
ALTER TABLE "public"."dba_datamodelversion" ALTER COLUMN "versiontext" TYPE text;
ALTER TABLE "public"."dba_dbstatstime" ALTER COLUMN "stattable" TYPE text;
ALTER TABLE "public"."dba_fielddescription" ALTER COLUMN "fieldnulls" TYPE text;
ALTER TABLE "public"."dba_fielddescription" ALTER COLUMN "fieldname" TYPE text;
ALTER TABLE "public"."dba_fielddescription" ALTER COLUMN "fieldlabel" TYPE text;
ALTER TABLE "public"."dba_fielddescription" ALTER COLUMN "fieldmodel" TYPE text;
ALTER TABLE "public"."dba_fielddescription" ALTER COLUMN "fieldtype" TYPE text;
ALTER TABLE "public"."dba_fielddescription" ALTER COLUMN "fieldkey" TYPE text;
ALTER TABLE "public"."dba_fielddescription" ALTER COLUMN "fieldreferences" TYPE text;
ALTER TABLE "public"."dba_fielddescription" ALTER COLUMN "tablename" TYPE text;
ALTER TABLE "public"."dba_fielddescription" ALTER COLUMN "fieldlist" TYPE text;
ALTER TABLE "public"."dba_fieldlist" ALTER COLUMN "fieldname" TYPE text;
ALTER TABLE "public"."dba_fieldlist" ALTER COLUMN "listvalue" TYPE text;
ALTER TABLE "public"."dba_fieldlist" ALTER COLUMN "tablename" TYPE text;
ALTER TABLE "public"."dba_preassignacccode" ALTER COLUMN "accessioncode" TYPE text;
ALTER TABLE "public"."dba_preassignacccode" ALTER COLUMN "confirmcode" TYPE text;
ALTER TABLE "public"."dba_preassignacccode" ALTER COLUMN "databasekey" TYPE text;
ALTER TABLE "public"."dba_preassignacccode" ALTER COLUMN "tableabbrev" TYPE text;
ALTER TABLE "public"."dba_tabledescription" ALTER COLUMN "tablename" TYPE text;
ALTER TABLE "public"."dba_tabledescription" ALTER COLUMN "tablelabel" TYPE text;
ALTER TABLE "public"."dba_xmlcache" ALTER COLUMN "accessioncode" TYPE text;
ALTER TABLE "public"."disturbanceobs" ALTER COLUMN "disturbancetype" TYPE text;
ALTER TABLE "public"."disturbanceobs" ALTER COLUMN "disturbanceintensity" TYPE text;
ALTER TABLE "public"."flyway_schema_history" ALTER COLUMN "installed_by" TYPE text;
ALTER TABLE "public"."flyway_schema_history" ALTER COLUMN "script" TYPE text;
ALTER TABLE "public"."flyway_schema_history" ALTER COLUMN "type" TYPE text;
ALTER TABLE "public"."flyway_schema_history" ALTER COLUMN "description" TYPE text;
ALTER TABLE "public"."flyway_schema_history" ALTER COLUMN "version" TYPE text;
ALTER TABLE "public"."graphic" ALTER COLUMN "graphicname" TYPE text;
ALTER TABLE "public"."graphic" ALTER COLUMN "accessioncode" TYPE text;
ALTER TABLE "public"."graphic" ALTER COLUMN "graphictype" TYPE text;
ALTER TABLE "public"."namedplace" ALTER COLUMN "placecode" TYPE text;
ALTER TABLE "public"."namedplace" ALTER COLUMN "owner" TYPE text;
ALTER TABLE "public"."namedplace" ALTER COLUMN "placesystem" TYPE text;
ALTER TABLE "public"."namedplace" ALTER COLUMN "placename" TYPE text;
ALTER TABLE "public"."namedplace" ALTER COLUMN "accessioncode" TYPE text;
ALTER TABLE "public"."namedplacecorrelation" ALTER COLUMN "placeconvergence" TYPE text;
ALTER TABLE "public"."note" ALTER COLUMN "notetype" TYPE text;
ALTER TABLE "public"."note" ALTER COLUMN "accessioncode" TYPE text;
ALTER TABLE "public"."notelink" ALTER COLUMN "tablename" TYPE text;
ALTER TABLE "public"."notelink" ALTER COLUMN "attributename" TYPE text;
ALTER TABLE "public"."observation" ALTER COLUMN "effortlevel" TYPE text;
ALTER TABLE "public"."observation" ALTER COLUMN "authorobscode" TYPE text;
ALTER TABLE "public"."observation" ALTER COLUMN "dateaccuracy" TYPE text;
ALTER TABLE "public"."observation" ALTER COLUMN "coverdispersion" TYPE text;
ALTER TABLE "public"."observation" ALTER COLUMN "stemsamplemethod" TYPE text;
ALTER TABLE "public"."observation" ALTER COLUMN "floristicquality" TYPE text;
ALTER TABLE "public"."observation" ALTER COLUMN "bryophytequality" TYPE text;
ALTER TABLE "public"."observation" ALTER COLUMN "lichenquality" TYPE text;
ALTER TABLE "public"."observation" ALTER COLUMN "homogeneity" TYPE text;
ALTER TABLE "public"."observation" ALTER COLUMN "phenologicaspect" TYPE text;
ALTER TABLE "public"."observation" ALTER COLUMN "representativeness" TYPE text;
ALTER TABLE "public"."observation" ALTER COLUMN "standmaturity" TYPE text;
ALTER TABLE "public"."observation" ALTER COLUMN "hydrologicregime" TYPE text;
ALTER TABLE "public"."observation" ALTER COLUMN "soilmoistureregime" TYPE text;
ALTER TABLE "public"."observation" ALTER COLUMN "soildrainage" TYPE text;
ALTER TABLE "public"."observation" ALTER COLUMN "watersalinity" TYPE text;
ALTER TABLE "public"."observation" ALTER COLUMN "soiltaxonsrc" TYPE text;
ALTER TABLE "public"."observation" ALTER COLUMN "nameother" TYPE text;
ALTER TABLE "public"."observation" ALTER COLUMN "dominantstratum" TYPE text;
ALTER TABLE "public"."observation" ALTER COLUMN "growthform1type" TYPE text;
ALTER TABLE "public"."observation" ALTER COLUMN "growthform2type" TYPE text;
ALTER TABLE "public"."observation" ALTER COLUMN "growthform3type" TYPE text;
ALTER TABLE "public"."observation" ALTER COLUMN "accessioncode" TYPE text;
ALTER TABLE "public"."observation" ALTER COLUMN "toptaxon1name" TYPE text;
ALTER TABLE "public"."observation" ALTER COLUMN "toptaxon2name" TYPE text;
ALTER TABLE "public"."observation" ALTER COLUMN "toptaxon3name" TYPE text;
ALTER TABLE "public"."observation" ALTER COLUMN "toptaxon4name" TYPE text;
ALTER TABLE "public"."observation" ALTER COLUMN "toptaxon5name" TYPE text;
ALTER TABLE "public"."observationsynonym" ALTER COLUMN "accessioncode" TYPE text;
ALTER TABLE "public"."party" ALTER COLUMN "middlename" TYPE text;
ALTER TABLE "public"."party" ALTER COLUMN "accessioncode" TYPE text;
ALTER TABLE "public"."party" ALTER COLUMN "partytype" TYPE text;
ALTER TABLE "public"."party" ALTER COLUMN "email" TYPE text;
ALTER TABLE "public"."party" ALTER COLUMN "organizationname" TYPE text;
ALTER TABLE "public"."party" ALTER COLUMN "surname" TYPE text;
ALTER TABLE "public"."party" ALTER COLUMN "salutation" TYPE text;
ALTER TABLE "public"."party" ALTER COLUMN "givenname" TYPE text;
ALTER TABLE "public"."plantconcept" ALTER COLUMN "plantcode" TYPE text;
ALTER TABLE "public"."plantconcept" ALTER COLUMN "plantname" TYPE text;
ALTER TABLE "public"."plantconcept" ALTER COLUMN "accessioncode" TYPE text;
ALTER TABLE "public"."plantcorrelation" ALTER COLUMN "plantconvergence" TYPE text;
ALTER TABLE "public"."plantname" ALTER COLUMN "plantname" TYPE text;
ALTER TABLE "public"."plantstatus" ALTER COLUMN "accessioncode" TYPE text;
ALTER TABLE "public"."plantstatus" ALTER COLUMN "plantconceptstatus" TYPE text;
ALTER TABLE "public"."plantstatus" ALTER COLUMN "plantparentname" TYPE text;
ALTER TABLE "public"."plantstatus" ALTER COLUMN "plantlevel" TYPE text;
ALTER TABLE "public"."plantusage" ALTER COLUMN "plantname" TYPE text;
ALTER TABLE "public"."plantusage" ALTER COLUMN "acceptedsynonym" TYPE text;
ALTER TABLE "public"."plantusage" ALTER COLUMN "plantnamestatus" TYPE text;
ALTER TABLE "public"."plantusage" ALTER COLUMN "classsystem" TYPE text;
ALTER TABLE "public"."plot" ALTER COLUMN "authordatum" TYPE text;
ALTER TABLE "public"."plot" ALTER COLUMN "accessioncode" TYPE text;
ALTER TABLE "public"."plot" ALTER COLUMN "authorplotcode" TYPE text;
ALTER TABLE "public"."plot" ALTER COLUMN "confidentialityreason" TYPE text;
ALTER TABLE "public"."plot" ALTER COLUMN "authore" TYPE text;
ALTER TABLE "public"."plot" ALTER COLUMN "submitter_email" TYPE text;
ALTER TABLE "public"."plot" ALTER COLUMN "submitter_givenname" TYPE text;
ALTER TABLE "public"."plot" ALTER COLUMN "submitter_surname" TYPE text;
ALTER TABLE "public"."plot" ALTER COLUMN "country" TYPE text;
ALTER TABLE "public"."plot" ALTER COLUMN "stateprovince" TYPE text;
ALTER TABLE "public"."plot" ALTER COLUMN "rocktype" TYPE text;
ALTER TABLE "public"."plot" ALTER COLUMN "surficialdeposits" TYPE text;
ALTER TABLE "public"."plot" ALTER COLUMN "landform" TYPE text;
ALTER TABLE "public"."plot" ALTER COLUMN "topoposition" TYPE text;
ALTER TABLE "public"."plot" ALTER COLUMN "placementmethod" TYPE text;
ALTER TABLE "public"."plot" ALTER COLUMN "standsize" TYPE text;
ALTER TABLE "public"."plot" ALTER COLUMN "shape" TYPE text;
ALTER TABLE "public"."plot" ALTER COLUMN "authorlocation" TYPE text;
ALTER TABLE "public"."plot" ALTER COLUMN "authorn" TYPE text;
ALTER TABLE "public"."plot" ALTER COLUMN "authorzone" TYPE text;
ALTER TABLE "public"."project" ALTER COLUMN "accessioncode" TYPE text;
ALTER TABLE "public"."project" ALTER COLUMN "projectname" TYPE text;
ALTER TABLE "public"."projectcontributor" ALTER COLUMN "surname" TYPE text;
ALTER TABLE "public"."projectcontributor" ALTER COLUMN "cheatrole" TYPE text;
ALTER TABLE "public"."reference" ALTER COLUMN "communicationtype" TYPE text;
ALTER TABLE "public"."reference" ALTER COLUMN "degree" TYPE text;
ALTER TABLE "public"."reference" ALTER COLUMN "accessioncode" TYPE text;
ALTER TABLE "public"."reference" ALTER COLUMN "shortname" TYPE text;
ALTER TABLE "public"."reference" ALTER COLUMN "publisher" TYPE text;
ALTER TABLE "public"."reference" ALTER COLUMN "publicationplace" TYPE text;
ALTER TABLE "public"."reference" ALTER COLUMN "isbn" TYPE text;
ALTER TABLE "public"."reference" ALTER COLUMN "edition" TYPE text;
ALTER TABLE "public"."reference" ALTER COLUMN "titlesuperior" TYPE text;
ALTER TABLE "public"."reference" ALTER COLUMN "title" TYPE text;
ALTER TABLE "public"."reference" ALTER COLUMN "referencetype" TYPE text;
ALTER TABLE "public"."reference" ALTER COLUMN "volume" TYPE text;
ALTER TABLE "public"."reference" ALTER COLUMN "issue" TYPE text;
ALTER TABLE "public"."reference" ALTER COLUMN "pagerange" TYPE text;
ALTER TABLE "public"."referencealtident" ALTER COLUMN "system" TYPE text;
ALTER TABLE "public"."referencealtident" ALTER COLUMN "identifier" TYPE text;
ALTER TABLE "public"."referencecontributor" ALTER COLUMN "roletype" TYPE text;
ALTER TABLE "public"."referencejournal" ALTER COLUMN "journal" TYPE text;
ALTER TABLE "public"."referencejournal" ALTER COLUMN "accessioncode" TYPE text;
ALTER TABLE "public"."referencejournal" ALTER COLUMN "abbreviation" TYPE text;
ALTER TABLE "public"."referencejournal" ALTER COLUMN "issn" TYPE text;
ALTER TABLE "public"."referenceparty" ALTER COLUMN "givenname" TYPE text;
ALTER TABLE "public"."referenceparty" ALTER COLUMN "surname" TYPE text;
ALTER TABLE "public"."referenceparty" ALTER COLUMN "suffix" TYPE text;
ALTER TABLE "public"."referenceparty" ALTER COLUMN "organizationname" TYPE text;
ALTER TABLE "public"."referenceparty" ALTER COLUMN "accessioncode" TYPE text;
ALTER TABLE "public"."referenceparty" ALTER COLUMN "salutation" TYPE text;
ALTER TABLE "public"."referenceparty" ALTER COLUMN "positionname" TYPE text;
ALTER TABLE "public"."referenceparty" ALTER COLUMN "type" TYPE text;
ALTER TABLE "public"."revision" ALTER COLUMN "previousvaluetype" TYPE text;
ALTER TABLE "public"."revision" ALTER COLUMN "tablename" TYPE text;
ALTER TABLE "public"."revision" ALTER COLUMN "tableattribute" TYPE text;
ALTER TABLE "public"."soilobs" ALTER COLUMN "soilhorizon" TYPE text;
ALTER TABLE "public"."soilobs" ALTER COLUMN "soilcolor" TYPE text;
ALTER TABLE "public"."soilobs" ALTER COLUMN "soiltexture" TYPE text;
ALTER TABLE "public"."soiltaxon" ALTER COLUMN "accessioncode" TYPE text;
ALTER TABLE "public"."soiltaxon" ALTER COLUMN "soilcode" TYPE text;
ALTER TABLE "public"."soiltaxon" ALTER COLUMN "soilname" TYPE text;
ALTER TABLE "public"."soiltaxon" ALTER COLUMN "soilframework" TYPE text;
ALTER TABLE "public"."stemlocation" ALTER COLUMN "stemcode" TYPE text;
ALTER TABLE "public"."stemlocation" ALTER COLUMN "stemhealth" TYPE text;
ALTER TABLE "public"."stratum" ALTER COLUMN "stratumname" TYPE text;
ALTER TABLE "public"."stratum" ALTER COLUMN "stratumdescription" TYPE text;
ALTER TABLE "public"."stratummethod" ALTER COLUMN "accessioncode" TYPE text;
ALTER TABLE "public"."stratummethod" ALTER COLUMN "stratumassignment" TYPE text;
ALTER TABLE "public"."stratummethod" ALTER COLUMN "stratummethodname" TYPE text;
ALTER TABLE "public"."stratumtype" ALTER COLUMN "stratumname" TYPE text;
ALTER TABLE "public"."stratumtype" ALTER COLUMN "stratumindex" TYPE text;
ALTER TABLE "public"."taxonalt" ALTER COLUMN "taxonaltconfidence" TYPE text;
ALTER TABLE "public"."taxonalt" ALTER COLUMN "taxonaltfit" TYPE text;
ALTER TABLE "public"."taxonimportance" ALTER COLUMN "covercode" TYPE text;
ALTER TABLE "public"."taxoninterpretation" ALTER COLUMN "taxonconfidence" TYPE text;
ALTER TABLE "public"."taxoninterpretation" ALTER COLUMN "museumaccessionnumber" TYPE text;
ALTER TABLE "public"."taxoninterpretation" ALTER COLUMN "grouptype" TYPE text;
ALTER TABLE "public"."taxoninterpretation" ALTER COLUMN "accessioncode" TYPE text;
ALTER TABLE "public"."taxoninterpretation" ALTER COLUMN "interpretationtype" TYPE text;
ALTER TABLE "public"."taxoninterpretation" ALTER COLUMN "taxonfit" TYPE text;
ALTER TABLE "public"."taxoninterpretation" ALTER COLUMN "collectionnumber" TYPE text;
ALTER TABLE "public"."taxonobservation" ALTER COLUMN "int_currplantcode" TYPE text;
ALTER TABLE "public"."taxonobservation" ALTER COLUMN "authorplantname" TYPE text;
ALTER TABLE "public"."taxonobservation" ALTER COLUMN "accessioncode" TYPE text;
ALTER TABLE "public"."taxonobservation" ALTER COLUMN "int_origplantscifull" TYPE text;
ALTER TABLE "public"."taxonobservation" ALTER COLUMN "int_origplantscinamenoauth" TYPE text;
ALTER TABLE "public"."taxonobservation" ALTER COLUMN "int_origplantcommon" TYPE text;
ALTER TABLE "public"."taxonobservation" ALTER COLUMN "int_origplantcode" TYPE text;
ALTER TABLE "public"."taxonobservation" ALTER COLUMN "int_currplantscifull" TYPE text;
ALTER TABLE "public"."taxonobservation" ALTER COLUMN "int_currplantscinamenoauth" TYPE text;
ALTER TABLE "public"."taxonobservation" ALTER COLUMN "int_currplantcommon" TYPE text;
ALTER TABLE "public"."telephone" ALTER COLUMN "phonenumber" TYPE text;
ALTER TABLE "public"."telephone" ALTER COLUMN "phonetype" TYPE text;
ALTER TABLE "public"."temp_ks_commconcept_acccodelist" ALTER COLUMN "accessioncode" TYPE text;
ALTER TABLE "public"."temptbl_std_commnames" ALTER COLUMN "translated" TYPE text;
ALTER TABLE "public"."temptbl_std_commnames" ALTER COLUMN "common" TYPE text;
ALTER TABLE "public"."temptbl_std_commnames" ALTER COLUMN "sciname" TYPE text;
ALTER TABLE "public"."temptbl_std_commnames" ALTER COLUMN "code" TYPE text;
ALTER TABLE "public"."temptbl_std_plantnames" ALTER COLUMN "scinamenoauth" TYPE text;
ALTER TABLE "public"."temptbl_std_plantnames" ALTER COLUMN "common" TYPE text;
ALTER TABLE "public"."temptbl_std_plantnames" ALTER COLUMN "sciname" TYPE text;
ALTER TABLE "public"."temptbl_std_plantnames" ALTER COLUMN "code" TYPE text;
ALTER TABLE "public"."temptbl_std_plantnames" ALTER COLUMN "plantname" TYPE text;
ALTER TABLE "public"."usercertification" ALTER COLUMN "degree_year" TYPE text;
ALTER TABLE "public"."usercertification" ALTER COLUMN "highest_degree" TYPE text;
ALTER TABLE "public"."usercertification" ALTER COLUMN "degree_institution" TYPE text;
ALTER TABLE "public"."usercertification" ALTER COLUMN "current_org" TYPE text;
ALTER TABLE "public"."usercertification" ALTER COLUMN "current_pos" TYPE text;
ALTER TABLE "public"."usercertification" ALTER COLUMN "esa_sponsor_name_a" TYPE text;
ALTER TABLE "public"."usercertification" ALTER COLUMN "esa_sponsor_email_a" TYPE text;
ALTER TABLE "public"."usercertification" ALTER COLUMN "esa_sponsor_name_b" TYPE text;
ALTER TABLE "public"."usercertification" ALTER COLUMN "esa_sponsor_email_b" TYPE text;
ALTER TABLE "public"."usercertification" ALTER COLUMN "certificationstatus" TYPE text;
ALTER TABLE "public"."userdataset" ALTER COLUMN "datasetname" TYPE text;
ALTER TABLE "public"."userdataset" ALTER COLUMN "datasettype" TYPE text;
ALTER TABLE "public"."userdataset" ALTER COLUMN "datasetsharing" TYPE text;
ALTER TABLE "public"."userdataset" ALTER COLUMN "datasetpassword" TYPE text;
ALTER TABLE "public"."userdataset" ALTER COLUMN "accessioncode" TYPE text;
ALTER TABLE "public"."userdatasetitem" ALTER COLUMN "itemaccessioncode" TYPE text;
ALTER TABLE "public"."userdatasetitem" ALTER COLUMN "itemtype" TYPE text;
ALTER TABLE "public"."userdatasetitem" ALTER COLUMN "externalaccessioncode" TYPE text;
ALTER TABLE "public"."userdatasetitem" ALTER COLUMN "itemtable" TYPE text;
ALTER TABLE "public"."userdatasetitem" ALTER COLUMN "itemdatabase" TYPE text;
ALTER TABLE "public"."userdefined" ALTER COLUMN "tablename" TYPE text;
ALTER TABLE "public"."userdefined" ALTER COLUMN "userdefinedtype" TYPE text;
ALTER TABLE "public"."userdefined" ALTER COLUMN "userdefinedcategory" TYPE text;
ALTER TABLE "public"."userdefined" ALTER COLUMN "userdefinedname" TYPE text;
ALTER TABLE "public"."userdefined" ALTER COLUMN "accessioncode" TYPE text;
ALTER TABLE "public"."usernotify" ALTER COLUMN "notifyname" TYPE text;
ALTER TABLE "public"."userpreference" ALTER COLUMN "preferencename" TYPE text;
ALTER TABLE "public"."userquery" ALTER COLUMN "querypassword" TYPE text;
ALTER TABLE "public"."userquery" ALTER COLUMN "querytype" TYPE text;
ALTER TABLE "public"."userquery" ALTER COLUMN "querysharing" TYPE text;
ALTER TABLE "public"."userquery" ALTER COLUMN "queryname" TYPE text;
ALTER TABLE "public"."userquery" ALTER COLUMN "accessioncode" TYPE text;
ALTER TABLE "public"."userrecordowner" ALTER COLUMN "tablename" TYPE text;
ALTER TABLE "public"."userrecordowner" ALTER COLUMN "ownertype" TYPE text;
ALTER TABLE "public"."userregionalexp" ALTER COLUMN "vegetation" TYPE text;
ALTER TABLE "public"."userregionalexp" ALTER COLUMN "floristics" TYPE text;
ALTER TABLE "public"."userregionalexp" ALTER COLUMN "nvc_ivc" TYPE text;
ALTER TABLE "public"."userregionalexp" ALTER COLUMN "region" TYPE text;
ALTER TABLE "public"."usr" ALTER COLUMN "password" TYPE text;
ALTER TABLE "public"."usr" ALTER COLUMN "preferred_name" TYPE text;
ALTER TABLE "public"."usr" ALTER COLUMN "remote_address" TYPE text;
ALTER TABLE "public"."usr" ALTER COLUMN "email_address" TYPE text;
----------------------------------------------------------------------------------------------------

----------------------------------------------------------------------------------------------------
-- Step 3: recreate all views
----------------------------------------------------------------------------------------------------
--
-- COPIED VERBATIM FROM helm/db/migrations/V1.4__create_vegbank_views.sql
--
CREATE VIEW view_party_public AS
SELECT party.party_id,
       accessioncode,
       salutation,
       surname,
       givenname,
       middlename,
       organizationname,
       contactinstructions,
       email
FROM party
         LEFT JOIN usr ON party.party_ID = usr.party_ID
WHERE usr.usr_id is NULL
   OR usr.permission_type > 1;
DROP VIEW IF EXISTS view_busRule_plotsizeshape;
CREATE VIEW view_busRule_plotsizeshape AS
SELECT (project_id),
       (
           select projectName
           from project
           where project.project_ID = observation.projecT_ID
       ) as projectName,
       count(1) as plotcount
from plot
         inner join observation on plot.plot_ID = observation.plot_ID
where (
          (area is null)
              and (
              shape is null
                  or (
                  ((shape) <> 'Plotless')
                      and (upper(shape) not like 'RELEV%')
                  )
              )
          )
group by project_ID;
DROP VIEW IF EXISTS view_busRule_duplStratumType;
CREATE VIEW view_busRule_duplStratumType AS
SELECT count(1),
       stratummethod_id,
       stratumindex
FROM stratumType
GROUP BY stratummethod_id,
         stratumindex
HAVING count(1) > 1;
DROP VIEW IF EXISTS view_busRule_duplcovercode;
CREATE VIEW view_busRule_duplcovercode AS
SELECT count(1),
       covermethod_id,
       covercode
FROM coverIndex
GROUP BY covermethod_id,
         covercode
HAVING count(1) > 1;
-- EMBARGO views
DROP VIEW IF EXISTS view_emb_embargo_complete;
DROP VIEW IF EXISTS view_emb_embargo_currentfullonly;
CREATE VIEW view_emb_embargo_currentfullonly AS
SELECT *
FROM embargo
WHERE (
          ((defaultStatus) = 6)
              AND ((embargoStart) < Now())
              AND ((embargoStop) > Now())
          );
CREATE VIEW view_emb_embargo_complete AS
SELECT Coalesce(emb.defaultStatus, 0) AS currentEmb,
       plot.plot_id
FROM plot
         LEFT JOIN view_emb_embargo_currentfullonly AS emb ON plot.PLOT_ID = emb.plot_ID;
CREATE VIEW view_notEmb_classContributor AS
SELECT *
FROM classContributor
where emb_classContributor < 6;
CREATE VIEW view_notEmb_commClass AS
SELECT *
FROM commClass
where emb_commClass < 6;
CREATE VIEW view_notEmb_commInterpretation AS
SELECT *
FROM commInterpretation
where emb_commInterpretation < 6;
CREATE VIEW view_notEmb_disturbanceObs AS
SELECT *
FROM disturbanceObs
where emb_disturbanceObs < 6;
CREATE VIEW view_notEmb_observation AS
SELECT *
FROM observation
where emb_observation < 6;
CREATE VIEW view_notEmb_observationContributor AS
SELECT observationContributor.*
FROM observationContributor
         inner join observation on observationContributor.observation_ID = observation.observation_ID
where observation.emb_observation < 6;
CREATE VIEW view_notEmb_plot AS
SELECT *
FROM plot
where emb_plot < 6;
CREATE VIEW view_notEmb_soilObs AS
SELECT *
FROM soilObs
where emb_soilObs < 6;
CREATE VIEW view_notEmb_stemCount AS
SELECT *
FROM stemCount
where emb_stemCount < 6;
CREATE VIEW view_notEmb_stemLocation AS
SELECT *
FROM stemLocation
where emb_stemLocation < 6;
CREATE VIEW view_notEmb_taxonAlt AS
SELECT *
FROM taxonAlt
where emb_taxonAlt < 6;
CREATE VIEW view_notEmb_taxonImportance AS
SELECT *
FROM taxonImportance
where emb_taxonImportance < 6;
CREATE VIEW view_notEmb_taxonInterpretation AS
SELECT *
FROM taxonInterpretation
where emb_taxonInterpretation < 6;
CREATE VIEW view_notEmb_taxonObservation AS
SELECT *
FROM taxonObservation
where emb_taxonObservation < 6;
CREATE VIEW view_export_classContributor AS
SELECT *
FROM view_notemb_classContributor;
CREATE VIEW view_export_commClass AS
SELECT *
FROM view_notemb_commClass;
CREATE VIEW view_export_commInterpretation AS
SELECT *
FROM view_notemb_commInterpretation;
CREATE VIEW view_export_disturbanceObs AS
SELECT *
FROM view_notemb_disturbanceObs;
CREATE VIEW view_export_observation AS
SELECT *
FROM view_notemb_observation;
CREATE VIEW view_export_observationcontributor AS
SELECT *
FROM view_notemb_observationcontributor;
-- PLOT requires shifting field names to remove some fields for confidential plots
CREATE VIEW view_export_plot_pre AS
SELECT plot_id,
       authorplotcode,
       reference_id,
       parent_id,
       locationaccuracy,
       confidentialitystatus,
       latitude,
       longitude,
       CASE
           WHEN confidentialitystatus > 0 THEN null
           ELSE authorlocation
           END as authorlocation_emb,
       CASE
           WHEN confidentialitystatus > 0 THEN null
           ELSE locationnarrative
           END as locationnarrative_emb,
       azimuth,
       dsgpoly,
       shape,
       area,
       standsize,
       placementmethod,
       permanence,
       layoutnarrative,
       elevation,
       elevationaccuracy,
       elevationrange,
       slopeaspect,
       minslopeaspect,
       maxslopeaspect,
       slopegradient,
       minslopegradient,
       maxslopegradient,
       topoposition,
       landform,
       surficialdeposits,
       rocktype,
       stateprovince,
       country,
       submitter_surname,
       submitter_givenname,
       submitter_email,
       notespublic,
       notesmgt,
       revisions,
       dateentered,
       emb_plot,
       plotrationalenarrative,
       accessioncode
FROM view_notemb_plot;
CREATE VIEW view_export_plot AS
SELECT plot_id,
       authorplotcode,
       reference_id,
       parent_id,
       locationaccuracy,
       confidentialitystatus,
       latitude,
       longitude,
       authorlocation_emb as authorlocation,
       locationnarrative_emb as locationnarrative,
       azimuth,
       dsgpoly,
       shape,
       area,
       standsize,
       placementmethod,
       permanence,
       layoutnarrative,
       elevation,
       elevationaccuracy,
       elevationrange,
       slopeaspect,
       minslopeaspect,
       maxslopeaspect,
       slopegradient,
       minslopegradient,
       maxslopegradient,
       topoposition,
       landform,
       surficialdeposits,
       rocktype,
       stateprovince,
       country,
       submitter_surname,
       submitter_givenname,
       submitter_email,
       notespublic,
       notesmgt,
       revisions,
       dateentered,
       emb_plot,
       plotrationalenarrative,
       accessioncode
FROM view_export_plot_pre;
CREATE VIEW view_export_soilObs AS
SELECT *
FROM view_notemb_soilObs;
CREATE VIEW view_export_stemCount AS
SELECT *
FROM view_notemb_stemCount;
CREATE VIEW view_export_stemLocation AS
SELECT *
FROM view_notemb_stemLocation;
CREATE VIEW view_export_taxonAlt AS
SELECT *
FROM view_notemb_taxonAlt;
CREATE VIEW view_export_taxonImportance AS
SELECT *
FROM view_notemb_taxonImportance;
CREATE VIEW view_export_taxonInterpretation AS
SELECT *
FROM view_notemb_taxonInterpretation;
CREATE VIEW view_export_taxonObservation AS
SELECT *
FROM view_notemb_taxonObservation;
------------------
-- END EMBARGO VIEWS
-------------------
CREATE VIEW view_reference_transl AS
SELECT CASE
           WHEN shortName IS NULL THEN CASE
                                           WHEN title IS NULL THEN CASE
                                                                       WHEN fulltext IS NULL THEN '[poorly documented reference]'
                                                                       ELSE CASE
                                                                                WHEN length(fulltext) > 35 THEN substr(fulltext, 1, 32) || '...'
                                                                                ELSE fulltext
                                                                           END
                                               END
                                           ELSE title
               END
           ELSE shortName
           END AS reference_id_transl,
       reference_id
from reference;
CREATE VIEW view_plantconcept_transl AS
SELECT plantconcept_id,
       plantname_id,
       plantname,
       reference_id,
       plantname || ' [' || (
           select reference_id_transl
           FROM view_reference_transl
           where view_reference_transl.reference_id = plantconcept.reference_id
       ) || ']' as plantconcept_id_transl
FROM plantconcept;
CREATE VIEW view_commconcept_transl AS
SELECT commconcept_id,
       commname_id,
       commname,
       reference_id,
       commname || ' [' || (
           select reference_id_transl
           FROM view_reference_transl
           where view_reference_transl.reference_id = commconcept.reference_id
       ) || ']' as commconcept_id_transl
FROM commconcept;
CREATE VIEW view_party_transl AS
SELECT CASE
           WHEN surname is null THEN CASE
                                         WHEN organizationname IS NULL THEN '[poorly documented party]'
                                         ELSE organizationname || ' (organization)'
               END
           ELSE surname || CASE
                               WHEN givenname IS NULL THEN ''
                               ELSE ', ' || COALESCE(givenname, '')
               END
           END AS party_id_transl,
       party_id
FROM party;
--- browsing by party views: -----
CREATE VIEW view_browseparty_obscontrib AS
SELECT observationContributor.PARTY_ID,
       observationContributor.OBSERVATION_ID
FROM view_notemb_observation as observation
         INNER JOIN observationContributor ON observation.OBSERVATION_ID = observationContributor.OBSERVATION_ID
GROUP BY observationContributor.PARTY_ID,
         observationContributor.OBSERVATION_ID;
CREATE VIEW view_browseparty_projectcontrib AS
SELECT observation_1.OBSERVATION_ID,
       projectContributor.PARTY_ID
FROM (
         project
             INNER JOIN view_notemb_observation AS observation_1 ON project.PROJECT_ID = observation_1.PROJECT_ID
     )
         INNER JOIN projectContributor ON project.PROJECT_ID = projectContributor.PROJECT_ID
GROUP BY observation_1.OBSERVATION_ID,
         projectContributor.PARTY_ID;
CREATE VIEW view_browseparty_classcontrib AS
SELECT observation_2.OBSERVATION_ID,
       classContributor.PARTY_ID
FROM view_notemb_observation AS observation_2
         INNER JOIN (
    commClass
        INNER JOIN classContributor ON commClass.COMMCLASS_ID = classContributor.COMMCLASS_ID
) ON observation_2.OBSERVATION_ID = commClass.OBSERVATION_ID
GROUP BY observation_2.OBSERVATION_ID,
         classContributor.PARTY_ID;
CREATE VIEW view_browseparty_all AS
SELECT OBSERVATION_ID,
       PARTY_ID
FROM view_browseparty_classcontrib
union
SELECT OBSERVATION_ID,
       PARTY_ID
FROM view_browseparty_projectcontrib
UNION
SELECT OBSERVATION_ID,
       PARTY_ID
FROM view_browseparty_obscontrib;
CREATE VIEW view_browseparty_all_count AS
SELECT count(1) AS countallcontrib,
       party_ID
FROM view_browseparty_all
GROUP BY party_ID;
CREATE VIEW view_browseparty_classcontrib_count AS
SELECT count(1) AS countclasscontrib,
       party_ID
FROM view_browseparty_classcontrib
GROUP BY party_ID;
CREATE VIEW view_browseparty_obscontrib_count AS
SELECT count(1) AS countobscontrib,
       party_ID
FROM view_browseparty_obscontrib
GROUP BY party_ID;
CREATE VIEW view_browseparty_projectcontrib_count AS
SELECT count(1) AS countprojectcontrib,
       party_ID
FROM view_browseparty_projectcontrib
GROUP BY party_ID;
CREATE VIEW view_browseparty_all_count_combined AS
SELECT view_browseparty_all_count.party_ID,
       view_browseparty_all_count.countallcontrib,
       view_browseparty_classcontrib_count.countclasscontrib,
       view_browseparty_obscontrib_count.countobscontrib,
       view_browseparty_projectcontrib_count.countprojectcontrib
FROM (
         (
             view_browseparty_all_count
                 LEFT JOIN view_browseparty_classcontrib_count ON view_browseparty_all_count.party_ID = view_browseparty_classcontrib_count.party_ID
         )
             LEFT JOIN view_browseparty_obscontrib_count ON view_browseparty_all_count.party_ID = view_browseparty_obscontrib_count.party_ID
         )
         LEFT JOIN view_browseparty_projectcontrib_count ON view_browseparty_all_count.party_ID = view_browseparty_projectcontrib_count.party_ID
ORDER BY countallcontrib DESC;
CREATE view view_csv_taxonimportance_pre AS
SELECT taxonobservation.observation_id AS observation_ID,
       authorplantname AS plant,
       (
           CASE
               WHEN (taxonimportance.stratum_id is null) THEN '-all-'
               ELSE (
                   SELECT stratumtype.stratumname
                   FROM stratumtype,
                        stratum
                   WHERE stratum.stratumtype_id = stratumtype.stratumtype_id
                     AND stratum.stratum_id = taxonimportance.stratum_id
               )
               END
           ) AS stratum,
       cover,
       (
           select min(coverIndex.coverCode)
           from coverIndex
           where coverPercent = taxonimportance.cover
             AND coverIndex.coverMethod_ID = observation.coverMethod_ID
             and observation.observation_ID = taxonobservation.observation_ID
       ) as coverCode_exact,
       (
           select min(coverIndex.coverCode)
           from coverIndex
           where upperlimit >= taxonimportance.cover
             and lowerlimit <= taxonimportance.cover
             AND coverIndex.coverMethod_ID = observation.coverMethod_ID
             and observation.observation_ID = taxonobservation.observation_ID
       ) as coverCode_byrange,
       taxonimportance.basalarea,
       taxonobservation.accessioncode
FROM taxonobservation,
     taxonimportance,
     view_notemb_observation AS observation
WHERE taxonobservation.taxonobservation_id = taxonimportance.taxonobservation_id
  AND taxonobservation.observation_ID = observation.observation_ID;
CREATE view view_csv_taxonimportance AS
SELECT observation_ID,
       plant,
       stratum,
       cover,
       CASE
           WHEN (covercode_exact is null) THEN covercode_byrange
           ELSE covercode_exact
           END as covercode,
       basalarea,
       accessioncode
FROM view_csv_taxonimportance_pre;
-- the following views create "standard" names for plantconcepts, based on usages of preferred party and classsystems:
DROP VIEW IF EXISTS view_std_plantnames_code;
CREATE VIEW view_std_plantnames_code AS
SELECT plantconcept_id,
       plantname
FROM plantusage
WHERE classsystem = 'Code'
  AND party_id = (
    SELECT party_id
    FROM party
    WHERE accessioncode = 'VB.Py.511.USDANRCSPLANTS2'
)
  AND usagestop IS NULL;
DROP VIEW IF EXISTS view_std_plantnames_sciname;
CREATE VIEW view_std_plantnames_sciname AS
SELECT plantconcept_id,
       plantname
FROM plantusage
WHERE classsystem = 'Scientific'
  AND party_id = (
    SELECT party_id
    FROM party
    WHERE accessioncode = 'VB.Py.511.USDANRCSPLANTS2'
)
  AND usagestop IS NULL;
DROP VIEW IF EXISTS view_std_plantnames_scinamenoauth;
CREATE VIEW view_std_plantnames_scinamenoauth AS
SELECT plantconcept_id,
       plantname
FROM plantusage
WHERE classsystem = 'Scientific without authors'
  AND party_id = (
    SELECT party_id
    FROM party
    WHERE accessioncode = 'VB.Py.511.USDANRCSPLANTS2'
)
  AND usagestop IS NULL;
DROP VIEW IF EXISTS view_std_plantnames_common;
CREATE VIEW view_std_plantnames_common AS
SELECT plantconcept_id,
       plantname
FROM plantusage
WHERE classsystem = 'English Common'
  AND party_id = (
    SELECT party_id
    FROM party
    WHERE accessioncode = 'VB.Py.511.USDANRCSPLANTS2'
)
  AND usagestop IS NULL;
--the following views are same as above, but not party specific, to catch "other concepts":
DROP VIEW IF EXISTS view_all_plantnames_code;
CREATE VIEW view_all_plantnames_code AS
SELECT plantconcept_id,
       plantname
FROM plantusage
WHERE classsystem = 'Code';
DROP VIEW IF EXISTS view_all_plantnames_sciname;
CREATE VIEW view_all_plantnames_sciname AS
SELECT plantconcept_id,
       plantname
FROM plantusage
WHERE classsystem = 'Scientific';
DROP VIEW IF EXISTS view_all_plantnames_scinamenoauth;
CREATE VIEW view_all_plantnames_scinamenoauth AS
SELECT plantconcept_id,
       plantname
FROM plantusage
WHERE classsystem = 'Scientific without authors';
DROP VIEW IF EXISTS view_all_plantnames_common;
CREATE VIEW view_all_plantnames_common AS
SELECT plantconcept_id,
       plantname
FROM plantusage
WHERE classsystem = 'English Common';
-- the following views create "standard" names for commconcepts, based on usages of preferred party and classsystems:
DROP VIEW IF EXISTS view_std_commnames_code;
CREATE VIEW view_std_commnames_code AS
SELECT commconcept_id,
       commname
FROM commusage
WHERE classsystem = 'Code'
  AND party_id = (
    SELECT party_id
    FROM party
    WHERE accessioncode = 'VB.Py.512.NATURESERVE'
)
  AND usagestop IS NULL;
DROP VIEW IF EXISTS view_std_commnames_sciname;
CREATE VIEW view_std_commnames_sciname AS
SELECT commconcept_id,
       commname
FROM commusage
WHERE classsystem = 'Scientific'
  AND party_id = (
    SELECT party_id
    FROM party
    WHERE accessioncode = 'VB.Py.512.NATURESERVE'
)
  AND usagestop IS NULL;
DROP VIEW IF EXISTS view_std_commnames_translated;
CREATE VIEW view_std_commnames_translated AS
SELECT commconcept_id,
       commname
FROM commusage
WHERE classsystem = 'Translated'
  AND party_id = (
    SELECT party_id
    FROM party
    WHERE accessioncode = 'VB.Py.512.NATURESERVE'
)
  AND usagestop IS NULL;
DROP VIEW IF EXISTS view_std_commnames_common;
CREATE VIEW view_std_commnames_common AS
SELECT commconcept_id,
       commname
FROM commusage
WHERE classsystem = 'Common'
  AND party_id = (
    SELECT party_id
    FROM party
    WHERE accessioncode = 'VB.Py.512.NATURESERVE'
)
  AND usagestop IS NULL;
DROP VIEW IF EXISTS view_all_commnames_code;
CREATE VIEW view_all_commnames_code AS
SELECT commconcept_id,
       commname
FROM commusage
WHERE classsystem = 'Code';
DROP VIEW IF EXISTS view_all_commnames_sciname;
CREATE VIEW view_all_commnames_sciname AS
SELECT commconcept_id,
       commname
FROM commusage
WHERE classsystem = 'Scientific';
DROP VIEW IF EXISTS view_all_commnames_translated;
CREATE VIEW view_all_commnames_translated AS
SELECT commconcept_id,
       commname
FROM commusage
WHERE classsystem = 'Translated';
DROP VIEW IF EXISTS view_all_commnames_common;
CREATE VIEW view_all_commnames_common AS
SELECT commconcept_id,
       commname
FROM commusage
WHERE classsystem = 'Common';
CREATE VIEW view_comminterp_more AS
SELECT commClass.observation_ID,
       inspection,
       tableanalysis,
       multivariateanalysis,
       expertsystem,
       classpublication_id,
       classnotes,
       accessioncode,
       classstartdate,
       classstopdate,
       comminterpretation.*,
       (
           CASE
               WHEN classfit = 'Absolutely wrong' THEN 6
               WHEN classfit = 'Understandable but wrong' THEN 4
               WHEN classfit = 'Reasonable or acceptable answer' THEN 3
               WHEN classfit = 'Good answer' THEN 2
               WHEN classfit = 'Absolutely correct' THEN 1
               ELSE 5
               END
           ) as classfitnum,
       (
           CASE
               WHEN classconfidence = 'High' THEN 1
               WHEN classconfidence = 'Medium' THEN 2
               WHEN classconfidence = 'Low' THEN 3
               ELSE 4
               END
           ) as classconfidencenum
FROM view_notemb_commClass as commclass,
     comminterpretation
WHERE commclass.commclass_ID = comminterpretation.commclass_ID;
CREATE VIEW view_taxonInterp_more AS
SELECT taxonInterpretation.*,
       plantconcept.accessionCode AS pc_accessioncode,
       plantconcept.plantname as pc_plantname,
       taxonobservation.observation_ID
FROM view_notEmb_taxonInterpretation as taxonInterpretation,
     taxonobservation,
     plantconcept
WHERE taxonobservation.taxonobservation_ID = taxonInterpretation.taxonobservation_ID
  AND plantconcept.plantconcept_id = taxonInterpretation.plantconcept_id;
CREATE VIEW view_observation_transl AS
SELECT observation_ID,
       COALESCE(authorObsCode, authorPlotCode) AS observation_id_transl
FROM view_notemb_observation as observation,
     plot
WHERE observation.plot_ID = plot.plot_ID;
-- CREATE VIEW view_taxonobs_distinctid_curr AS SELECT observation_id, int_currplantconcept_id as plantconcept_id, max(cover) as maxplantcover FROM view_notEmb_taxonObservation as taxonobservation,     taxonimportance where taxonimportance.taxonobservation_id=taxonobservation.taxonobservation_id GROUP BY plantconcept_id,observation_id;
-- this view needed in the event there are no taxonimportance records for a taxonobservation.
-- DROP VIEW IF EXISTS view_taxonobs_withmaxcover;
CREATE VIEW view_taxonobs_withmaxcover AS
SELECT taxonobservation.*,
       (
           select max(cover)
           from taxonimportance
           where taxonimportance.taxonobservation_ID = taxonobservation.taxonobservation_ID
       ) as maxcover
FROM view_notEmb_taxonObservation as taxonobservation;
--   DROP VIEW IF EXISTS view_taxonobs_distinctid_curr;
CREATE VIEW view_taxonobs_distinctid_curr AS
SELECT userdataset_id,
       observation_id,
       int_currplantconcept_id as plantconcept_id,
       max(maxcover) as maxplantcover
FROM view_taxonobs_withmaxcover as taxonobservation,
     userdatasetitem
WHERE observation_id = itemrecord
  AND itemtable = 'observation'
GROUP BY plantconcept_id,
         userdataset_id,
         observation_id;
-- DROP VIEW IF EXISTS view_taxonobs_distinctid_curr_counts;
CREATE VIEW view_taxonobs_distinctid_curr_counts AS
SELECT userdataset_id,
       plantconcept_id,
       count(1) AS countObs,
       avg(maxplantcover) AS avgcovernoround,
       min(maxplantcover) AS mincovernoround,
       max(maxplantcover) AS maxcovernoround
FROM view_taxonobs_distinctid_curr
GROUP BY userdataset_id,
         plantconcept_id;
-- DROP VIEW IF EXISTS view_taxonobs_distinctid_curr_counts_plants;
CREATE VIEW view_taxonobs_distinctid_curr_counts_plants AS
SELECT view_taxonobs_distinctid_curr_counts.*,
       round(
               CAST (
                       view_taxonobs_distinctid_curr_counts.avgcovernoround as numeric
               ),
               3
       ) AS avgcover,
       round(
               CAST (
                       view_taxonobs_distinctid_curr_counts.mincovernoround as numeric
               ),
               3
       ) AS mincover,
       round(
               CAST (
                       view_taxonobs_distinctid_curr_counts.maxcovernoround as numeric
               ),
               3
       ) AS maxcover,
       temptbl_std_plantnames.plantname,
       temptbl_std_plantnames.sciname,
       temptbl_std_plantnames.scinamenoauth,
       temptbl_std_plantnames.code,
       temptbl_std_plantnames.common
FROM temptbl_std_plantnames,
     view_taxonobs_distinctid_curr_counts
WHERE view_taxonobs_distinctid_curr_counts.plantconcept_ID = temptbl_std_plantnames.plantconcept_ID;
--DROP VIEW IF EXISTS view_plotall_withembargo;
CREATE VIEW view_plotall_withembargo AS
SELECT plot.*,
       embargo_id,
       embargoreason,
       defaultstatus,
       embargostart,
       embargostop,
       (
           defaultstatus + CASE
                               WHEN embargostop < now() then 100
                               ELSE 0
               END
           ) AS embstatusinclexpired
from plot
         LEFT JOIN embargo on plot.plot_id = embargo.plot_ID;
--CREATE VIEW view_taxonobs_distinctid_orig;
-- KEYWORDS VIEWS (otherwise they just aren't robust enough and are breaking!)
CREATE VIEW view_kwhelper_refjournal AS
SELECT reference.reference_id,
       coalesce(referencejournal.journal, '') || ' ' || coalesce(referencejournal.issn, '') || ' ' || coalesce(referencejournal.abbreviation, '') as kw
FROM reference,
     referencejournal
WHERE reference.referencejournal_id = referencejournal.referencejournal_id
GROUP BY reference.reference_id,
         referencejournal.journal,
         referencejournal.issn,
         referencejournal.abbreviation;
CREATE VIEW view_kwhelper_refparty AS
SELECT reference.reference_id,
       public.CONCAT(
               ' ' || coalesce(referenceparty.givenname, '') || ' ' || coalesce(referenceparty.surname, '') || ' ' || coalesce(referenceparty.suffix, '') || ' ' || coalesce(referenceparty.organizationname, '')
       ) as kw
FROM referenceparty,
     reference,
     referencecontributor
WHERE referencecontributor.referenceparty_id = referenceparty.referenceparty_id
  AND reference.reference_id = referencecontributor.reference_id
GROUP BY reference.reference_id;
CREATE VIEW view_keywProjPlaces AS
SELECT project.project_id,
       plot.stateProvince
FROM plot,
     project,
     observation
WHERE plot.plot_ID = observation.plot_ID
  AND project.project_id = observation.project_id
GROUP BY project.project_ID,
         plot.stateProvince;
CREATE VIEW view_kwhelper_projcontrib AS
SELECT project.project_id,
       public.CONCAT(
               ' ' || coalesce(party.givenname, '') || ' ' || coalesce(party.surname, '')
       ) as kw
FROM party,
     project,
     projectcontributor
WHERE party.party_id = projectcontributor.party_Id
  AND project.project_id = projectcontributor.project_id
GROUP BY project.project_id;
CREATE VIEW view_dbafielddesc_notimpl AS
SELECT dba_fielddescription_id,
       tablename,
       (
           SELECT tablelabel
           from dba_tabledescription
           WHERE dba_fielddescription.tablename = dba_tabledescription.tableName
           LIMIT 1
    ) AS tablename_transl,
    fieldname,
    fieldlabel,
    fieldmodel,
    fieldnulls,
    (
        CASE
            when fieldnulls = 'no' THEN 'required'
            ELSE 'no'
        END
    ) as fieldnulls_transl,
    fieldtype,
    fieldkey,
    (
        CASE
            WHEN fieldkey = 'PK' THEN fieldkey
            WHEN fieldkey = 'FK' THEN fieldkey
            WHEN fieldmodel = 'denorm' THEN fieldmodel
            WHEN fieldmodel = 'implementation' THEN fieldmodel
            ELSE 'n/a'
        END
    ) as fieldkey_transl,
    fieldreferences,
    fieldlist,
    fieldnotes,
    fielddefinition,
    fieldkeywords
FROM dba_fielddescription
WHERE lower(fieldmodel) <> 'implementation'
    and lower(fieldmodel) <> 'denorm'
ORDER BY dba_fielddescription_id;
create view stratumtype_x_stratummethod AS
select stratumType.*,
       stratumMethod.accessionCode as sm_accCode
from stratumType
         inner join stratummethod on stratumType.stratummethod_id = stratummethod.stratummethod_id;
create view stratumtype_x_observation AS
SELECT stratum.stratum_id,
       stratum.stratumname,
       observation.accessioncode
FROM observation
         JOIN stratum ON observation.observation_id = stratum.observation_id;

--
-- COPIED VERBATIM FROM helm/db/migrations/V1.8__populate_acc_identifiers_procedure.sql
--
CREATE VIEW acc_code_source_map AS
SELECT * FROM identifiers_source_map WHERE id_type = 'accession_code';

--
-- COPIED VERBATIM FROM helm/db/migrations/V1.9__populate_vb_identifiers_procedure.sql
--
CREATE VIEW vb_code_source_map AS
SELECT * FROM identifiers_source_map WHERE id_type = 'vb_code';
--------------------------------------------------------------------------------------
