######################################################################################
#     D O   N O T   C H E C K   C R E D E N T I A L S   I N T O   G I T H U B ! ! !
######################################################################################
#
# EZID API credentials for DOI minting and management.
# Apply manually: kubectl apply -f ezid-client-secret.yaml -n vegbank
#
apiVersion: v1
kind: Secret
metadata:
  name: vegbank-ezid-creds
type: kubernetes.io/basic-auth
## @param stringData write-only, non-binary secret data (eg credentials) in string form.
##
## # # #    NEVER CHECK SECRETS INTO GITHUB!   # # #
##
stringData:
  ## @param 'username'
  ## The EZID API username assigned to your institution/project.
  username: "apitest" # Replace with your actual EZID API username
  ## @param 'password'
  ## The EZID API password for the above username.
  password: "apitest" # Replace with your actual EZID API password
