######################################################################################
#     D O   N O T   C H E C K   C R E D E N T I A L S   I N T O   G I T H U B ! ! !
######################################################################################
#
# Credentials and secrets used by the VegBank API application.
# 
# Edit this file to add your credentials, then install them in your cluster by one of the
# following methods. Assuming your release name is "myrelease": (NOTE THE RELEASE NAME MUST
# MATCH THE ONE YOU USE WITH HELM!)
#
# 1. Define the release name on the command line:
#     $  RELEASE_NAME=myrelease  envsubst < secret.yaml | kubectl apply -n <mynamespace> -f -
#
#     # if this results in "command not found: envsubst", you can install envsubst (e.g. on Mac OS:
#        $  brew install gettext && brew link --force gettext
#
# 2. Alternatively, you can simply replace "${RELEASE_NAME}" in the file below (be sure to retain
#    the "-vegbank-secrets" part), and do:     
#     
#        $  kubectl apply -n <mynamespace> -f secret.yaml)
#
#
apiVersion: v1
kind: Secret
metadata:
  name: ${RELEASE_NAME}-vegbank-secrets
type: Opaque
## @param stringData write-only, non-binary secret data (eg credentials) in string form.
stringData:
  ## @param 'EZID_USERNAME'
  ## The EZID API username assigned to your institution/project.
  EZID_USERNAME: "YOUR-VALUE-HERE"
  ## @param 'EZID_PASSWORD'
  ## The EZID API password for the above username.
  EZID_PASSWORD: "YOUR-PASSWORD-HERE"
