SELECT
    'pl.' || plot.plot_id AS pl_code,
    'ob.' || observation.observation_id AS ob_code,
    authorPlotCode,
    confidentialityStatus,
    confidentialityReason,
    permanence,
    observation.obsStartDate,
    observation.obsEndDate,
    observation.taxonObservationArea,
    locationAccuracy,
    authorE,
    authorN,
    authorZone,
    authorDatum,
    authorLocation,
    locationNarrative,
    azimuth,
    shape,
    standSize,
    placementMethod,
    layoutNarrative,
    elevation,
    slopeAspect,
    slopeGradient,
    topoPosition,
    landform,
    rockType,
    surficialDeposits,
    methodNarrative,
    coverDispersion,
    originalData,
    effortLevel,
    floristicQuality,
    bryophyteQuality,
    lichenQuality,
    observationNarrative,
    landscapeNarrative,
    homogeneity,
    phenologicAspect,
    hydrologicRegime,
    soilmoistureRegime,
    soilDrainage,
    waterSalinity,
    waterDepth,
    shoreDistance,
    soilDepth,
    organicDepth,
    percentBedRock,
    percentRockGravel,
    percentWood,
    percentLitter,
    percentBareSoil,
    percentWater,
    percentOther,
    nameOther,
    stateProvince,
    country,
    dsgpoly,
    elevationAccuracy,
    elevationRange,
    minSlopeAspect,
    maxSlopeAspect,
    minSlopeGradient,
    maxSlopeGradient,
    authorObsCode,
    'ob.' || previousobs_id AS previous_ob_code,
    dateAccuracy,
    stemSizeLimit,
    autoTaxonCover,
    stemObservationArea,
    stemSampleMethod,
    basalArea,
    standMaturity,
    successionalStatus,
    treeHt,
    shrubHt,
    fieldHt,
    nonvascularHt,
    submergedHt,
    treeCover,
    shrubCover,
    fieldCover,
    nonvascularCover,
    floatingCover,
    submergedCover,
    dominantStratum,
    growthform1Type,
    growthform1Cover,
    growthform2Type,
    growthform2Cover,
    growthform3Type,
    growthform3Cover,
    totalCover,
    'st.' || soiltaxon_id AS st_code,
    soilTaxonSrc,
    'pl.' || parent_id AS parent_pl_code,
    'pj.' || project_id AS pj_code,
    'cm.' || covermethod_id AS cm_code,
    'sm.' || stratummethod.stratummethod_id AS sm_code,
    stratumMethod.stratumMethodName,
    stratumMethod.stratumMethodDescription,
    stratumMethod.stratumAssignment
FROM
    observation left join plot on observation.plot_id = plot.plot_id
    left join stratumMethod on observation.stratumMethod_ID = stratumMethod.stratumMethod_ID
WHERE 
    plot.confidentialityStatus < 4
    AND observation.observation_id = %s;
