SELECT
    authorPlotCode,
    'pl.' || plot.plot_id AS pl_code,
    'rf.' || reference_id AS rf_code,
    'pl.' || parent_id AS parent_pl_code,
    locationAccuracy,
    confidentialityStatus,
    confidentialityReason,
    latitude,
    longitude,
    authorE,
    authorN,
    authorZone,
    authorDatum,
    authorLocation,
    locationNarrative,
    azimuth,
    dsgpoly,
    shape,
    area,
    standSize,
    placementMethod,
    permanence,
    layoutNarrative,
    elevation,
    elevationAccuracy,
    elevationRange,
    slopeAspect,
    minSlopeAspect,
    maxSlopeAspect,
    slopeGradient,
    minSlopeGradient,
    maxSlopeGradient,
    topoPosition,
    landform,
    surficialDeposits,
    rockType,
    plot.country,
    plot.stateprovince,
    plot.notesPublic AS plotNotesPublic,
    plot.notesMgt AS plotNotesMgt,
    plot.revisions AS plotRevisions,
    'ob.' || observation.observation_id AS ob_code,
    'ob.' || observation.previousobs_id AS previous_ob_code,
    'pj.' || observation.project_id AS pj_code,
    observation.authorobscode,            
    observation.obsstartdate,             
    observation.obsenddate,               
    observation.dateaccuracy,             
    observation.dateentered,              
    'cm.' || observation.covermethod_id AS cm_code,
    observation.coverdispersion,          
    observation.autotaxoncover,           
    'sm.' || observation.stratummethod_id AS sm_code,
    observation.methodnarrative,          
    observation.taxonobservationarea,     
    observation.stemsizelimit,            
    observation.stemobservationarea,      
    observation.stemsamplemethod,         
    observation.originaldata,             
    observation.effortlevel,              
    observation.plotvalidationlevel,      
    observation.floristicquality,         
    observation.bryophytequality,         
    observation.lichenquality,            
    observation.observationnarrative,     
    observation.landscapenarrative,       
    observation.homogeneity,              
    observation.phenologicaspect,         
    observation.representativeness,       
    observation.standmaturity,            
    observation.successionalstatus,       
    observation.numberoftaxa,             
    observation.basalarea,                
    observation.hydrologicregime,         
    observation.soilmoistureregime,       
    observation.soildrainage,             
    observation.watersalinity,            
    observation.waterdepth,               
    observation.shoredistance,            
    observation.soildepth,                
    observation.organicdepth,             
    'st.' || observation.soiltaxon_id AS st_code,
    observation.soiltaxonsrc,             
    observation.percentbedrock,           
    observation.percentrockgravel,        
    observation.percentwood,              
    observation.percentlitter,            
    observation.percentbaresoil,          
    observation.percentwater,             
    observation.percentother,             
    observation.nameother,                
    observation.treeht,                   
    observation.shrubht,                  
    observation.fieldht,                  
    observation.nonvascularht,            
    observation.submergedht,              
    observation.treecover,                
    observation.shrubcover,               
    observation.fieldcover,               
    observation.nonvascularcover,         
    observation.floatingcover,            
    observation.submergedcover,           
    observation.dominantstratum,          
    observation.growthform1type,          
    observation.growthform2type,          
    observation.growthform3type,          
    observation.growthform1cover,         
    observation.growthform2cover,         
    observation.growthform3cover,         
    observation.totalcover,               
    observation.notespublic AS obsNotesPublic,              
    observation.notesmgt AS obsNotesMgt,                 
    observation.revisions AS obsRevisions,                
    observation.emb_observation,          
    'ci.' || observation.interp_orig_ci_id AS interp_orig_ci_code,
    'cc.' || observation.interp_orig_cc_id AS interp_orig_cc_code,
    observation.interp_orig_sciname,      
    observation.interp_orig_code,         
    'py.' || observation.interp_orig_party_id AS interp_orig_py_code,
    observation.interp_orig_partyname,    
    'ci.' || observation.interp_current_ci_id AS interp_current_ci_code,
    'cc.' || observation.interp_current_cc_id AS interp_current_cc_code,
    observation.interp_current_sciname,   
    observation.interp_current_code,      
    'py.' || observation.interp_current_party_id AS interp_current_py_code,
    observation.interp_current_partyname, 
    'ci.' || observation.interp_bestfit_ci_id AS interp_bestfit_ci_code,
    'cc.' || observation.interp_bestfit_cc_id AS interp_bestfit_cc_code,
    observation.interp_bestfit_sciname,   
    observation.interp_bestfit_code,      
    'py.' || observation.interp_bestfit_party_id AS interp_bestfit_py_code,
    observation.interp_bestfit_partyname, 
    observation.toptaxon1name,            
    observation.toptaxon2name,            
    observation.toptaxon3name,            
    observation.toptaxon4name,            
    observation.toptaxon5name,            
    observation.hasobservationsynonym


FROM
    plot join observation on plot.plot_id = observation.plot_id
WHERE plot.confidentialityStatus < 4
ORDER BY observation.observation_ID ASC
LIMIT %s
OFFSET %s;


