CREATE TEMP TABLE observation_temp(
    ob_code character varying(30)  NOT NULL,
    previousobs_code character varying(30),
    pl_code character varying(30) NOT NULL,
    pj_code character varying(30),
    authorobscode character varying(30),
    obsstartdate timestamp with time zone,
    obsenddate timestamp with time zone,
    dateaccuracy character varying(30),
    dateentered timestamp with time zone DEFAULT now(),
    cm_code character varying(30),
    coverdispersion character varying(30),
    autotaxoncover boolean,
    sm_code character varying(30),
    methodnarrative text,
    taxonobservationarea double precision,
    stemsizelimit double precision,
    stemobservationarea double precision,
    stemsamplemethod character varying(30),
    originaldata text,
    effortlevel character varying(30),
    plotvalidationlevel integer,
    floristicquality character varying(30),
    bryophytequality character varying(30),
    lichenquality character varying(30),
    observationnarrative text,
    landscapenarrative text,
    homogeneity character varying(50),
    phenologicaspect character varying(30),
    representativeness character varying(255),
    standmaturity character varying(50),
    successionalstatus text,
    numberoftaxa integer,
    basalarea double precision,
    hydrologicregime character varying(255),
    soilmoistureregime character varying(30),
    soildrainage character varying(30),
    watersalinity character varying(30),
    waterdepth double precision,
    shoredistance double precision,
    soildepth double precision,
    organicdepth double precision,
    st_code character varying(30),
    soiltaxonsrc character varying(200),
    percentbedrock double precision,
    percentrockgravel double precision,
    percentwood double precision,
    percentlitter double precision,
    percentbaresoil double precision,
    percentwater double precision,
    percentother double precision,
    nameother character varying(30),
    treeht double precision,
    shrubht double precision,
    fieldht double precision,
    nonvascularht double precision,
    submergedht double precision,
    treecover double precision,
    shrubcover double precision,
    fieldcover double precision,
    nonvascularcover double precision,
    floatingcover double precision,
    submergedcover double precision,
    dominantstratum character varying(40),
    growthform1type character varying(40),
    growthform2type character varying(40),
    growthform3type character varying(40),
    growthform1cover double precision,
    growthform2cover double precision,
    growthform3cover double precision,
    totalcover double precision,
    accessioncode character varying(255),
    ob_notes_public boolean,
    ob_notes_mgt boolean,
    ob_revisions boolean,
    emb_observation integer,
    hasobservationsynonym boolean -- Not used, can this go away?
)