MERGE INTO observation dst
USING observation_temp src
ON FALSE
WHEN MATCHED THEN DO NOTHING
WHEN NOT MATCHED THEN
  INSERT (
    plot_id,
    project_id,
    authorobscode,
    obsstartdate,
    obsenddate,
    dateaccuracy,
    dateentered,
    covermethod_id,
    coverdispersion,
    autotaxoncover,
    stratummethod_id,
    methodnarrative,
    taxonobservationarea,
    stemsizelimit,
    stemobservationarea,
    stemsamplemethod,
    originaldata,
    effortlevel,
    floristicquality,
    bryophytequality,
    lichenquality,
    observationnarrative,
    landscapenarrative,
    homogeneity,
    phenologicaspect,
    standmaturity,
    successionalstatus,
    basalarea,
    hydrologicregime,
    soilmoistureregime,
    soildrainage,
    watersalinity,
    waterdepth,
    shoredistance,
    soildepth,
    organicdepth,
    soiltaxon_id,
    soiltaxonsrc,
    percentbedrock,
    percentrockgravel,
    percentwood,
    percentlitter,
    percentbaresoil,
    percentwater,
    percentother,
    nameother,
    treeht,
    shrubht,
    fieldht,
    nonvascularht,
    submergedht,
    treecover,
    shrubcover,
    fieldcover,
    nonvascularcover,
    floatingcover,
    submergedcover,
    dominantstratum,
    growthform1type,
    growthform2type,
    growthform3type,
    growthform1cover,
    growthform2cover,
    growthform3cover,
    totalcover,
    notespublic,
    notesmgt,
    hasobservationsynonym
  ) VALUES (
    CAST(SUBSTRING(vb_pl_code, 4) AS INT),
    CAST(SUBSTRING(vb_pj_code, 4) AS INT),
    authorobscode,
    obsstartdate,
    obsenddate,
    dateaccuracy,
    dateentered,
    CAST(SUBSTRING(vb_cm_code, 4) AS INT),
    coverdispersion,
    autotaxoncover,
    CAST(SUBSTRING(vb_sm_code, 4) AS INT),
    methodnarrative,
    taxonobservationarea,
    stemsizelimit,
    stemobservationarea,
    stemsamplemethod,
    originaldata,
    effortlevel,
    floristicquality,
    bryophytequality,
    lichenquality,
    observationnarrative,
    landscapenarrative,
    homogeneity,
    phenologicaspect,
    standmaturity,
    successionalstatus,
    basalarea,
    hydrologicregime,
    soilmoistureregime,
    soildrainage,
    watersalinity,
    waterdepth,
    shoredistance,
    soildepth,
    organicdepth,
    CAST(SUBSTRING(vb_so_code, 4) AS INT),
    soiltaxonsrc,
    percentbedrock,
    percentrockgravel,
    percentwood,
    percentlitter,
    percentbaresoil,
    percentwater,
    percentother,
    nameother,
    treeht,
    shrubht,
    fieldht,
    nonvascularht,
    submergedht,
    treecover,
    shrubcover,
    fieldcover,
    nonvascularcover,
    floatingcover,
    submergedcover,
    dominantstratum,
    growthform1type,
    growthform2type,
    growthform3type,
    growthform1cover,
    growthform2cover,
    growthform3cover,
    totalcover,
    ob_notes_public,
    ob_notes_mgt,
    hasobservationsynonym
  )
RETURNING merge_action(),
          src.user_ob_code,
          dst.observation_id,
          'ob.' || dst.observation_id AS vb_ob_code;