## Overrides common settings that need to be adjusted during testing and development.
##
## Example usage:
##
## # From the ./helm directory:
## $ helm upgrade vegbankapi . -f values-overrides-dev.yaml
##

## If not using an ingress, you will need to use port forwarding to access the API, e.g.:
## $ kubectl port-forward svc/vegbankapi 8080:80    # then access API at http://localhost:8080
##
ingress:
  enabled: false

## Uncomment if needed:
# databaseRestore:
#   enabled: true
#   filepath: "vegbank_full_fc_v1.9_pg16_20250924.dump"

image:
  ## Set image pull policy to 'Always' for development to ensure latest image is used
  pullPolicy: Always
  # tag: ""  # Override docker image version for development builds
