openapi: '3.0.3'
info:
  title: VegBankAPIUpload
  version: '0.1'
servers:
  - url: https://api.server.test/v1

paths:
  /vegbank/upload/party-information:
    get: 
      responses: 
        "200":
          description: returns a parquet binary file according to the list of accession codes you provided. 
          content:
            "party-information.parquet": 
              "schema":
                "type": "string"
                "format": "binary"
    post: 
      requestBody: 
        content:
          "party-information-input.parquet": 
            "schema":
              "type": "string"
              "format": "binary" 
      responses: 
        "200":
          description: returns a list of accession codes for new parties uploaded
        "403": 
          description: you do not have permission to upload this data. 
        "409": #Does this error code also get used for "Your data is formed incorrectly?"
          description: a record you tried to insert already exists.  

  /vegbank/upload/plot-data:
    get: 
      responses: 
        "200":
          description: returns a parquet binary file with data according to the list of accession codes you provided. 
          content:
            "plot-data.parquet": 
              "schema":
                "type": "string"
                "format": "binary"
    post: 
      requestBody: 
        content:
          "plot-data-input.parquet": 
            "schema":
              "type": "string"
              "format": "binary" 
      responses: 
        "200":
          description: returns a list of accession codes for new plots and observations uploaded
        "403": 
          description: you do not have permission to upload this data. 
        "409": #Does this error code also get used for "Your data is formed incorrectly?"
          description: a record you tried to insert already exists.    

  /vegbank/upload/presence-data:
    get: 
      responses: 
        "200":
          description: returns a parquet binary file with data according to the list of accession codes you provided. 
          content:
            "presence-data.parquet": 
              "schema":
                "type": "string"
                "format": "binary"
    post: 
      requestBody: 
        content:
          "presence-data-input.parquet": 
            "schema":
              "type": "string"
              "format": "binary" 
      responses: 
        "200":
          description: returns a list of accession codes for new plots and observations uploaded
        "403": 
          description: you do not have permission to upload this data. 
        "409": #Does this error code also get used for "Your data is formed incorrectly?"
          description: a record you tried to insert already exists.  

  /vegbank/upload/strata-cover-data: #Possible that stratum method/type need to be looped into this request. Question for Michael. 
    get: 
      responses: 
        "200":
          description: returns a parquet binary file with data according to the list of accession codes you provided. 
          content:
            "strata-cover-data.parquet": 
              "schema":
                "type": "string"
                "format": "binary"
    post: 
      requestBody: 
        content:
          "presence-data-input.parquet": 
            "schema":
              "type": "string"
              "format": "binary" 
      responses: 
        "200":
          description: returns a list of accession codes for new strata uploaded
        "403": 
          description: you do not have permission to upload this data. 
        "409": #Does this error code also get used for "Your data is formed incorrectly?"
          description: a record you tried to insert already exists.  

  /vegbank/upload/plot-normalized-data: 
    get: 
      responses: 
        "200":
          description: returns a parquet binary file with data according to the list of accession codes you provided. 
          content:
            "plot-normalized.parquet": 
              "schema":
                "type": "string"
                "format": "binary"
    post: 
      requestBody: 
        content:
          "plot-normalized-data-input.parquet": 
            "schema":
              "type": "string"
              "format": "binary" 
      responses: 
        "200":
          description: returns a list of accession codes for new plots and observations uploaded
        "403": 
          description: you do not have permission to upload this data. 
        "409": #Does this error code also get used for "Your data is formed incorrectly?"
          description: a record you tried to insert already exists.    

  /vegbank/upload/community-concepts: 
    get: 
      responses: 
        "200":
          description: returns a parquet binary file with data according to the list of accession codes you provided. 
          content:
            "community-concepts.parquet": 
              "schema":
                "type": "string"
                "format": "binary"
    post: 
      requestBody: 
        content:
          "community-concepts-input.parquet": 
            "schema":
              "type": "string"
              "format": "binary" 
      responses: 
        "200":
          description: returns a list of accession codes for new community concepts uploaded
        "403": 
          description: you do not have permission to upload this data. 
        "409": #Does this error code also get used for "Your data is formed incorrectly?"
          description: a record you tried to insert already exists.         

  /vegbank/upload/species-list: 
    get: 
      responses: 
        "200":
          description: returns a parquet binary file with data according to the list of accession codes you provided. 
          content:
            "species-list.parquet": 
              "schema":
                "type": "string"
                "format": "binary"
    post: 
      requestBody: 
        content:
          "species-list-input.parquet": 
            "schema":
              "type": "string"
              "format": "binary" 
      responses: 
        "200":
          description: returns a list of accession codes for new species uploaded
        "403": 
          description: you do not have permission to upload this data. 
        "409": #Does this error code also get used for "Your data is formed incorrectly?"
          description: a record you tried to insert already exists.       

  /vegbank/upload/stem-data: 
    get: 
      responses: 
        "200":
          description: returns a parquet binary file with data according to the list of accession codes you provided. 
          content:
            "stem-data.parquet": 
              "schema":
                "type": "string"
                "format": "binary"
    post: 
      requestBody: 
        content:
          "stem-data-input.parquet": 
            "schema":
              "type": "string"
              "format": "binary" 
      responses: 
        "200":
          description: returns a list of accession codes for new stems uploaded
        "403": 
          description: you do not have permission to upload this data. 
        "409": #Does this error code also get used for "Your data is formed incorrectly?"
          description: a record you tried to insert already exists.  

  /vegbank/upload/plot-communities: 
    get: 
      responses: 
        "200":
          description: returns a parquet binary file with data according to the list of accession codes you provided. 
          content:
            "plot-communities.parquet": 
              "schema":
                "type": "string"
                "format": "binary"
    post: 
      requestBody: 
        content:
          "plot-communities-input.parquet": 
            "schema":
              "type": "string"
              "format": "binary" 
      responses: 
        "200":
          description: returns a list of accession codes for new species uploaded
        "403": 
          description: you do not have permission to upload this data. 
        "409": #Does this error code also get used for "Your data is formed incorrectly?"
          description: a record you tried to insert already exists.  